// GENERATED by MiNET.BlockGen from MiNET.BdsExtract/Data items-runtime.json.
// Do not hand-edit. Run the tool again after updating the source data.

namespace MiNET.Items
{

	public partial class ItemAcaciaBoat : Item // minecraft:acacia_boat
	{
		public ItemAcaciaBoat() : base("minecraft:acacia_boat") { }
	} // class

	public partial class ItemAcaciaChestBoat : Item // minecraft:acacia_chest_boat
	{
		public ItemAcaciaChestBoat() : base("minecraft:acacia_chest_boat") { }
	} // class

	public partial class ItemAgentSpawnEgg : Item // minecraft:agent_spawn_egg
	{
		public ItemAgentSpawnEgg() : base("minecraft:agent_spawn_egg") { }
	} // class

	public partial class ItemAllaySpawnEgg : Item // minecraft:allay_spawn_egg
	{
		public ItemAllaySpawnEgg() : base("minecraft:allay_spawn_egg") { }
	} // class

	public partial class ItemAmethystShard : Item // minecraft:amethyst_shard
	{
		public ItemAmethystShard() : base("minecraft:amethyst_shard") { }
	} // class

	public partial class ItemAnglerPotterySherd : Item // minecraft:angler_pottery_sherd
	{
		public ItemAnglerPotterySherd() : base("minecraft:angler_pottery_sherd") { }
	} // class

	public partial class ItemArcherPotterySherd : Item // minecraft:archer_pottery_sherd
	{
		public ItemArcherPotterySherd() : base("minecraft:archer_pottery_sherd") { }
	} // class

	public partial class ItemArmadilloScute : Item // minecraft:armadillo_scute
	{
		public ItemArmadilloScute() : base("minecraft:armadillo_scute") { }
	} // class

	public partial class ItemArmadilloSpawnEgg : Item // minecraft:armadillo_spawn_egg
	{
		public ItemArmadilloSpawnEgg() : base("minecraft:armadillo_spawn_egg") { }
	} // class

	public partial class ItemArmsUpPotterySherd : Item // minecraft:arms_up_pottery_sherd
	{
		public ItemArmsUpPotterySherd() : base("minecraft:arms_up_pottery_sherd") { }
	} // class

	public partial class ItemAxolotlBucket : Item // minecraft:axolotl_bucket
	{
		public ItemAxolotlBucket() : base("minecraft:axolotl_bucket") { }
	} // class

	public partial class ItemAxolotlSpawnEgg : Item // minecraft:axolotl_spawn_egg
	{
		public ItemAxolotlSpawnEgg() : base("minecraft:axolotl_spawn_egg") { }
	} // class

	public partial class ItemBambooChestRaft : Item // minecraft:bamboo_chest_raft
	{
		public ItemBambooChestRaft() : base("minecraft:bamboo_chest_raft") { }
	} // class

	public partial class ItemBambooRaft : Item // minecraft:bamboo_raft
	{
		public ItemBambooRaft() : base("minecraft:bamboo_raft") { }
	} // class

	public partial class ItemBambooSign : Item // minecraft:bamboo_sign
	{
		public ItemBambooSign() : base("minecraft:bamboo_sign") { }
	} // class

	public partial class ItemBatSpawnEgg : Item // minecraft:bat_spawn_egg
	{
		public ItemBatSpawnEgg() : base("minecraft:bat_spawn_egg") { }
	} // class

	public partial class ItemBeeSpawnEgg : Item // minecraft:bee_spawn_egg
	{
		public ItemBeeSpawnEgg() : base("minecraft:bee_spawn_egg") { }
	} // class

	public partial class ItemBirchBoat : Item // minecraft:birch_boat
	{
		public ItemBirchBoat() : base("minecraft:birch_boat") { }
	} // class

	public partial class ItemBirchChestBoat : Item // minecraft:birch_chest_boat
	{
		public ItemBirchChestBoat() : base("minecraft:birch_chest_boat") { }
	} // class

	public partial class ItemBlackBundle : Item // minecraft:black_bundle
	{
		public ItemBlackBundle() : base("minecraft:black_bundle") { }
	} // class

	public partial class ItemBlackCushion : Item // minecraft:black_cushion
	{
		public ItemBlackCushion() : base("minecraft:black_cushion") { }
	} // class

	public partial class ItemBlackDye : Item // minecraft:black_dye
	{
		public ItemBlackDye() : base("minecraft:black_dye") { }
	} // class

	public partial class ItemBlackHarness : Item // minecraft:black_harness
	{
		public ItemBlackHarness() : base("minecraft:black_harness") { }
	} // class

	public partial class ItemBladePotterySherd : Item // minecraft:blade_pottery_sherd
	{
		public ItemBladePotterySherd() : base("minecraft:blade_pottery_sherd") { }
	} // class

	public partial class ItemBlazeSpawnEgg : Item // minecraft:blaze_spawn_egg
	{
		public ItemBlazeSpawnEgg() : base("minecraft:blaze_spawn_egg") { }
	} // class

	public partial class ItemBlueBundle : Item // minecraft:blue_bundle
	{
		public ItemBlueBundle() : base("minecraft:blue_bundle") { }
	} // class

	public partial class ItemBlueCushion : Item // minecraft:blue_cushion
	{
		public ItemBlueCushion() : base("minecraft:blue_cushion") { }
	} // class

	public partial class ItemBlueDye : Item // minecraft:blue_dye
	{
		public ItemBlueDye() : base("minecraft:blue_dye") { }
	} // class

	public partial class ItemBlueEgg : Item // minecraft:blue_egg
	{
		public ItemBlueEgg() : base("minecraft:blue_egg") { }
	} // class

	public partial class ItemBlueHarness : Item // minecraft:blue_harness
	{
		public ItemBlueHarness() : base("minecraft:blue_harness") { }
	} // class

	public partial class ItemBoggedSpawnEgg : Item // minecraft:bogged_spawn_egg
	{
		public ItemBoggedSpawnEgg() : base("minecraft:bogged_spawn_egg") { }
	} // class

	public partial class ItemBoltArmorTrimSmithingTemplate : Item // minecraft:bolt_armor_trim_smithing_template
	{
		public ItemBoltArmorTrimSmithingTemplate() : base("minecraft:bolt_armor_trim_smithing_template") { }
	} // class

	public partial class ItemBoneMeal : Item // minecraft:bone_meal
	{
		public ItemBoneMeal() : base("minecraft:bone_meal") { }
	} // class

	public partial class ItemBordureIndentedBannerPattern : Item // minecraft:bordure_indented_banner_pattern
	{
		public ItemBordureIndentedBannerPattern() : base("minecraft:bordure_indented_banner_pattern") { }
	} // class

	public partial class ItemBreezeRod : Item // minecraft:breeze_rod
	{
		public ItemBreezeRod() : base("minecraft:breeze_rod") { }
	} // class

	public partial class ItemBreezeSpawnEgg : Item // minecraft:breeze_spawn_egg
	{
		public ItemBreezeSpawnEgg() : base("minecraft:breeze_spawn_egg") { }
	} // class

	public partial class ItemBrewerPotterySherd : Item // minecraft:brewer_pottery_sherd
	{
		public ItemBrewerPotterySherd() : base("minecraft:brewer_pottery_sherd") { }
	} // class

	public partial class ItemBrownBundle : Item // minecraft:brown_bundle
	{
		public ItemBrownBundle() : base("minecraft:brown_bundle") { }
	} // class

	public partial class ItemBrownCushion : Item // minecraft:brown_cushion
	{
		public ItemBrownCushion() : base("minecraft:brown_cushion") { }
	} // class

	public partial class ItemBrownDye : Item // minecraft:brown_dye
	{
		public ItemBrownDye() : base("minecraft:brown_dye") { }
	} // class

	public partial class ItemBrownEgg : Item // minecraft:brown_egg
	{
		public ItemBrownEgg() : base("minecraft:brown_egg") { }
	} // class

	public partial class ItemBrownHarness : Item // minecraft:brown_harness
	{
		public ItemBrownHarness() : base("minecraft:brown_harness") { }
	} // class

	public partial class ItemBrush : Item // minecraft:brush
	{
		public ItemBrush() : base("minecraft:brush") { }
	} // class

	public partial class ItemBundle : Item // minecraft:bundle
	{
		public ItemBundle() : base("minecraft:bundle") { }
	} // class

	public partial class ItemBurnPotterySherd : Item // minecraft:burn_pottery_sherd
	{
		public ItemBurnPotterySherd() : base("minecraft:burn_pottery_sherd") { }
	} // class

	public partial class ItemCamelHuskSpawnEgg : Item // minecraft:camel_husk_spawn_egg
	{
		public ItemCamelHuskSpawnEgg() : base("minecraft:camel_husk_spawn_egg") { }
	} // class

	public partial class ItemCamelSpawnEgg : Item // minecraft:camel_spawn_egg
	{
		public ItemCamelSpawnEgg() : base("minecraft:camel_spawn_egg") { }
	} // class

	public partial class ItemCarpet : Item // minecraft:carpet
	{
		public ItemCarpet() : base("minecraft:carpet") { }
	} // class

	public partial class ItemCatSpawnEgg : Item // minecraft:cat_spawn_egg
	{
		public ItemCatSpawnEgg() : base("minecraft:cat_spawn_egg") { }
	} // class

	public partial class ItemCaveSpiderSpawnEgg : Item // minecraft:cave_spider_spawn_egg
	{
		public ItemCaveSpiderSpawnEgg() : base("minecraft:cave_spider_spawn_egg") { }
	} // class

	public partial class ItemCharcoal : Item // minecraft:charcoal
	{
		public ItemCharcoal() : base("minecraft:charcoal") { }
	} // class

	public partial class ItemChemistryTable : Item // minecraft:chemistry_table
	{
		public ItemChemistryTable() : base("minecraft:chemistry_table") { }
	} // class

	public partial class ItemCherryBoat : Item // minecraft:cherry_boat
	{
		public ItemCherryBoat() : base("minecraft:cherry_boat") { }
	} // class

	public partial class ItemCherryChestBoat : Item // minecraft:cherry_chest_boat
	{
		public ItemCherryChestBoat() : base("minecraft:cherry_chest_boat") { }
	} // class

	public partial class ItemCherrySign : Item // minecraft:cherry_sign
	{
		public ItemCherrySign() : base("minecraft:cherry_sign") { }
	} // class

	public partial class ItemChestBoat : Item // minecraft:chest_boat
	{
		public ItemChestBoat() : base("minecraft:chest_boat") { }
	} // class

	public partial class ItemChickenSpawnEgg : Item // minecraft:chicken_spawn_egg
	{
		public ItemChickenSpawnEgg() : base("minecraft:chicken_spawn_egg") { }
	} // class

	public partial class ItemCoastArmorTrimSmithingTemplate : Item // minecraft:coast_armor_trim_smithing_template
	{
		public ItemCoastArmorTrimSmithingTemplate() : base("minecraft:coast_armor_trim_smithing_template") { }
	} // class

	public partial class ItemCocoaBeans : Item // minecraft:cocoa_beans
	{
		public ItemCocoaBeans() : base("minecraft:cocoa_beans") { }
	} // class

	public partial class ItemCodBucket : Item // minecraft:cod_bucket
	{
		public ItemCodBucket() : base("minecraft:cod_bucket") { }
	} // class

	public partial class ItemCodSpawnEgg : Item // minecraft:cod_spawn_egg
	{
		public ItemCodSpawnEgg() : base("minecraft:cod_spawn_egg") { }
	} // class

	public partial class ItemColoredTorchBp : Item // minecraft:colored_torch_bp
	{
		public ItemColoredTorchBp() : base("minecraft:colored_torch_bp") { }
	} // class

	public partial class ItemColoredTorchRg : Item // minecraft:colored_torch_rg
	{
		public ItemColoredTorchRg() : base("minecraft:colored_torch_rg") { }
	} // class

	public partial class ItemConcrete : Item // minecraft:concrete
	{
		public ItemConcrete() : base("minecraft:concrete") { }
	} // class

	public partial class ItemConcretePowder : Item // minecraft:concrete_powder
	{
		public ItemConcretePowder() : base("minecraft:concrete_powder") { }
	} // class

	public partial class ItemCookedMutton : Item // minecraft:cooked_mutton
	{
		public ItemCookedMutton() : base("minecraft:cooked_mutton") { }
	} // class

	public partial class ItemCopperAxe : ItemAxe // minecraft:copper_axe
	{
		public ItemCopperAxe() : base("minecraft:copper_axe") { }
	} // class

	public partial class ItemCopperBoots : ArmorBootsBase // minecraft:copper_boots
	{
		public ItemCopperBoots() : base("minecraft:copper_boots") { }
	} // class

	public partial class ItemCopperChestplate : ArmorChestplateBase // minecraft:copper_chestplate
	{
		public ItemCopperChestplate() : base("minecraft:copper_chestplate") { }
	} // class

	public partial class ItemCopperGolemSpawnEgg : Item // minecraft:copper_golem_spawn_egg
	{
		public ItemCopperGolemSpawnEgg() : base("minecraft:copper_golem_spawn_egg") { }
	} // class

	public partial class ItemCopperHelmet : ArmorHelmetBase // minecraft:copper_helmet
	{
		public ItemCopperHelmet() : base("minecraft:copper_helmet") { }
	} // class

	public partial class ItemCopperHoe : ItemHoe // minecraft:copper_hoe
	{
		public ItemCopperHoe() : base("minecraft:copper_hoe") { }
	} // class

	public partial class ItemCopperHorseArmor : Item // minecraft:copper_horse_armor
	{
		public ItemCopperHorseArmor() : base("minecraft:copper_horse_armor") { }
	} // class

	public partial class ItemCopperIngot : Item // minecraft:copper_ingot
	{
		public ItemCopperIngot() : base("minecraft:copper_ingot") { }
	} // class

	public partial class ItemCopperLeggings : ArmorLeggingsBase // minecraft:copper_leggings
	{
		public ItemCopperLeggings() : base("minecraft:copper_leggings") { }
	} // class

	public partial class ItemCopperNautilusArmor : Item // minecraft:copper_nautilus_armor
	{
		public ItemCopperNautilusArmor() : base("minecraft:copper_nautilus_armor") { }
	} // class

	public partial class ItemCopperNugget : Item // minecraft:copper_nugget
	{
		public ItemCopperNugget() : base("minecraft:copper_nugget") { }
	} // class

	public partial class ItemCopperPickaxe : ItemPickaxe // minecraft:copper_pickaxe
	{
		public ItemCopperPickaxe() : base("minecraft:copper_pickaxe") { }
	} // class

	public partial class ItemCopperShovel : ItemShovel // minecraft:copper_shovel
	{
		public ItemCopperShovel() : base("minecraft:copper_shovel") { }
	} // class

	public partial class ItemCopperSpear : Item // minecraft:copper_spear
	{
		public ItemCopperSpear() : base("minecraft:copper_spear") { }
	} // class

	public partial class ItemCopperSword : ItemSword // minecraft:copper_sword
	{
		public ItemCopperSword() : base("minecraft:copper_sword") { }
	} // class

	public partial class ItemCoral : Item // minecraft:coral
	{
		public ItemCoral() : base("minecraft:coral") { }
	} // class

	public partial class ItemCoralBlock : Item // minecraft:coral_block
	{
		public ItemCoralBlock() : base("minecraft:coral_block") { }
	} // class

	public partial class ItemCoralFan : Item // minecraft:coral_fan
	{
		public ItemCoralFan() : base("minecraft:coral_fan") { }
	} // class

	public partial class ItemCoralFanDead : Item // minecraft:coral_fan_dead
	{
		public ItemCoralFanDead() : base("minecraft:coral_fan_dead") { }
	} // class

	public partial class ItemCowSpawnEgg : Item // minecraft:cow_spawn_egg
	{
		public ItemCowSpawnEgg() : base("minecraft:cow_spawn_egg") { }
	} // class

	public partial class ItemCreakingSpawnEgg : Item // minecraft:creaking_spawn_egg
	{
		public ItemCreakingSpawnEgg() : base("minecraft:creaking_spawn_egg") { }
	} // class

	public partial class ItemCreeperBannerPattern : Item // minecraft:creeper_banner_pattern
	{
		public ItemCreeperBannerPattern() : base("minecraft:creeper_banner_pattern") { }
	} // class

	public partial class ItemCreeperSpawnEgg : Item // minecraft:creeper_spawn_egg
	{
		public ItemCreeperSpawnEgg() : base("minecraft:creeper_spawn_egg") { }
	} // class

	public partial class ItemCyanBundle : Item // minecraft:cyan_bundle
	{
		public ItemCyanBundle() : base("minecraft:cyan_bundle") { }
	} // class

	public partial class ItemCyanCushion : Item // minecraft:cyan_cushion
	{
		public ItemCyanCushion() : base("minecraft:cyan_cushion") { }
	} // class

	public partial class ItemCyanDye : Item // minecraft:cyan_dye
	{
		public ItemCyanDye() : base("minecraft:cyan_dye") { }
	} // class

	public partial class ItemCyanHarness : Item // minecraft:cyan_harness
	{
		public ItemCyanHarness() : base("minecraft:cyan_harness") { }
	} // class

	public partial class ItemDangerPotterySherd : Item // minecraft:danger_pottery_sherd
	{
		public ItemDangerPotterySherd() : base("minecraft:danger_pottery_sherd") { }
	} // class

	public partial class ItemDarkOakBoat : Item // minecraft:dark_oak_boat
	{
		public ItemDarkOakBoat() : base("minecraft:dark_oak_boat") { }
	} // class

	public partial class ItemDarkOakChestBoat : Item // minecraft:dark_oak_chest_boat
	{
		public ItemDarkOakChestBoat() : base("minecraft:dark_oak_chest_boat") { }
	} // class

	public partial class ItemDiamondNautilusArmor : Item // minecraft:diamond_nautilus_armor
	{
		public ItemDiamondNautilusArmor() : base("minecraft:diamond_nautilus_armor") { }
	} // class

	public partial class ItemDiamondSpear : Item // minecraft:diamond_spear
	{
		public ItemDiamondSpear() : base("minecraft:diamond_spear") { }
	} // class

	public partial class ItemDiscFragment5 : Item // minecraft:disc_fragment_5
	{
		public ItemDiscFragment5() : base("minecraft:disc_fragment_5") { }
	} // class

	public partial class ItemDolphinSpawnEgg : Item // minecraft:dolphin_spawn_egg
	{
		public ItemDolphinSpawnEgg() : base("minecraft:dolphin_spawn_egg") { }
	} // class

	public partial class ItemDonkeySpawnEgg : Item // minecraft:donkey_spawn_egg
	{
		public ItemDonkeySpawnEgg() : base("minecraft:donkey_spawn_egg") { }
	} // class

	public partial class ItemDoublePlant : Item // minecraft:double_plant
	{
		public ItemDoublePlant() : base("minecraft:double_plant") { }
	} // class

	public partial class ItemDoubleStoneBlockSlab : Item // minecraft:double_stone_block_slab
	{
		public ItemDoubleStoneBlockSlab() : base("minecraft:double_stone_block_slab") { }
	} // class

	public partial class ItemDoubleStoneBlockSlab2 : Item // minecraft:double_stone_block_slab2
	{
		public ItemDoubleStoneBlockSlab2() : base("minecraft:double_stone_block_slab2") { }
	} // class

	public partial class ItemDoubleStoneBlockSlab3 : Item // minecraft:double_stone_block_slab3
	{
		public ItemDoubleStoneBlockSlab3() : base("minecraft:double_stone_block_slab3") { }
	} // class

	public partial class ItemDoubleStoneBlockSlab4 : Item // minecraft:double_stone_block_slab4
	{
		public ItemDoubleStoneBlockSlab4() : base("minecraft:double_stone_block_slab4") { }
	} // class

	public partial class ItemDrownedSpawnEgg : Item // minecraft:drowned_spawn_egg
	{
		public ItemDrownedSpawnEgg() : base("minecraft:drowned_spawn_egg") { }
	} // class

	public partial class ItemDuneArmorTrimSmithingTemplate : Item // minecraft:dune_armor_trim_smithing_template
	{
		public ItemDuneArmorTrimSmithingTemplate() : base("minecraft:dune_armor_trim_smithing_template") { }
	} // class

	public partial class ItemEchoShard : Item // minecraft:echo_shard
	{
		public ItemEchoShard() : base("minecraft:echo_shard") { }
	} // class

	public partial class ItemElderGuardianSpawnEgg : Item // minecraft:elder_guardian_spawn_egg
	{
		public ItemElderGuardianSpawnEgg() : base("minecraft:elder_guardian_spawn_egg") { }
	} // class

	public partial class ItemEnchantedGoldenApple : Item // minecraft:enchanted_golden_apple
	{
		public ItemEnchantedGoldenApple() : base("minecraft:enchanted_golden_apple") { }
	} // class

	public partial class ItemEnderDragonSpawnEgg : Item // minecraft:ender_dragon_spawn_egg
	{
		public ItemEnderDragonSpawnEgg() : base("minecraft:ender_dragon_spawn_egg") { }
	} // class

	public partial class ItemEndermanSpawnEgg : Item // minecraft:enderman_spawn_egg
	{
		public ItemEndermanSpawnEgg() : base("minecraft:enderman_spawn_egg") { }
	} // class

	public partial class ItemEndermiteSpawnEgg : Item // minecraft:endermite_spawn_egg
	{
		public ItemEndermiteSpawnEgg() : base("minecraft:endermite_spawn_egg") { }
	} // class

	public partial class ItemEvokerSpawnEgg : Item // minecraft:evoker_spawn_egg
	{
		public ItemEvokerSpawnEgg() : base("minecraft:evoker_spawn_egg") { }
	} // class

	public partial class ItemExplorerPotterySherd : Item // minecraft:explorer_pottery_sherd
	{
		public ItemExplorerPotterySherd() : base("minecraft:explorer_pottery_sherd") { }
	} // class

	public partial class ItemEyeArmorTrimSmithingTemplate : Item // minecraft:eye_armor_trim_smithing_template
	{
		public ItemEyeArmorTrimSmithingTemplate() : base("minecraft:eye_armor_trim_smithing_template") { }
	} // class

	public partial class ItemFence : Item // minecraft:fence
	{
		public ItemFence() : base("minecraft:fence") { }
	} // class

	public partial class ItemFieldMasonedBannerPattern : Item // minecraft:field_masoned_banner_pattern
	{
		public ItemFieldMasonedBannerPattern() : base("minecraft:field_masoned_banner_pattern") { }
	} // class

	public partial class ItemFlowArmorTrimSmithingTemplate : Item // minecraft:flow_armor_trim_smithing_template
	{
		public ItemFlowArmorTrimSmithingTemplate() : base("minecraft:flow_armor_trim_smithing_template") { }
	} // class

	public partial class ItemFlowBannerPattern : Item // minecraft:flow_banner_pattern
	{
		public ItemFlowBannerPattern() : base("minecraft:flow_banner_pattern") { }
	} // class

	public partial class ItemFlowPotterySherd : Item // minecraft:flow_pottery_sherd
	{
		public ItemFlowPotterySherd() : base("minecraft:flow_pottery_sherd") { }
	} // class

	public partial class ItemFlowerBannerPattern : Item // minecraft:flower_banner_pattern
	{
		public ItemFlowerBannerPattern() : base("minecraft:flower_banner_pattern") { }
	} // class

	public partial class ItemFoxSpawnEgg : Item // minecraft:fox_spawn_egg
	{
		public ItemFoxSpawnEgg() : base("minecraft:fox_spawn_egg") { }
	} // class

	public partial class ItemFriendPotterySherd : Item // minecraft:friend_pottery_sherd
	{
		public ItemFriendPotterySherd() : base("minecraft:friend_pottery_sherd") { }
	} // class

	public partial class ItemFrogSpawnEgg : Item // minecraft:frog_spawn_egg
	{
		public ItemFrogSpawnEgg() : base("minecraft:frog_spawn_egg") { }
	} // class

	public partial class ItemGhastSpawnEgg : Item // minecraft:ghast_spawn_egg
	{
		public ItemGhastSpawnEgg() : base("minecraft:ghast_spawn_egg") { }
	} // class

	public partial class ItemGlisteringMelonSlice : Item // minecraft:glistering_melon_slice
	{
		public ItemGlisteringMelonSlice() : base("minecraft:glistering_melon_slice") { }
	} // class

	public partial class ItemGlobeBannerPattern : Item // minecraft:globe_banner_pattern
	{
		public ItemGlobeBannerPattern() : base("minecraft:globe_banner_pattern") { }
	} // class

	public partial class ItemGlowBerries : Item // minecraft:glow_berries
	{
		public ItemGlowBerries() : base("minecraft:glow_berries") { }
	} // class

	public partial class ItemGlowInkSac : Item // minecraft:glow_ink_sac
	{
		public ItemGlowInkSac() : base("minecraft:glow_ink_sac") { }
	} // class

	public partial class ItemGlowSquidSpawnEgg : Item // minecraft:glow_squid_spawn_egg
	{
		public ItemGlowSquidSpawnEgg() : base("minecraft:glow_squid_spawn_egg") { }
	} // class

	public partial class ItemGlowStick : Item // minecraft:glow_stick
	{
		public ItemGlowStick() : base("minecraft:glow_stick") { }
	} // class

	public partial class ItemGoatHorn : Item // minecraft:goat_horn
	{
		public ItemGoatHorn() : base("minecraft:goat_horn") { }
	} // class

	public partial class ItemGoatSpawnEgg : Item // minecraft:goat_spawn_egg
	{
		public ItemGoatSpawnEgg() : base("minecraft:goat_spawn_egg") { }
	} // class

	public partial class ItemGoldenNautilusArmor : Item // minecraft:golden_nautilus_armor
	{
		public ItemGoldenNautilusArmor() : base("minecraft:golden_nautilus_armor") { }
	} // class

	public partial class ItemGoldenSpear : Item // minecraft:golden_spear
	{
		public ItemGoldenSpear() : base("minecraft:golden_spear") { }
	} // class

	public partial class ItemGrayBundle : Item // minecraft:gray_bundle
	{
		public ItemGrayBundle() : base("minecraft:gray_bundle") { }
	} // class

	public partial class ItemGrayCushion : Item // minecraft:gray_cushion
	{
		public ItemGrayCushion() : base("minecraft:gray_cushion") { }
	} // class

	public partial class ItemGrayDye : Item // minecraft:gray_dye
	{
		public ItemGrayDye() : base("minecraft:gray_dye") { }
	} // class

	public partial class ItemGrayHarness : Item // minecraft:gray_harness
	{
		public ItemGrayHarness() : base("minecraft:gray_harness") { }
	} // class

	public partial class ItemGreenBundle : Item // minecraft:green_bundle
	{
		public ItemGreenBundle() : base("minecraft:green_bundle") { }
	} // class

	public partial class ItemGreenCushion : Item // minecraft:green_cushion
	{
		public ItemGreenCushion() : base("minecraft:green_cushion") { }
	} // class

	public partial class ItemGreenDye : Item // minecraft:green_dye
	{
		public ItemGreenDye() : base("minecraft:green_dye") { }
	} // class

	public partial class ItemGreenHarness : Item // minecraft:green_harness
	{
		public ItemGreenHarness() : base("minecraft:green_harness") { }
	} // class

	public partial class ItemGuardianSpawnEgg : Item // minecraft:guardian_spawn_egg
	{
		public ItemGuardianSpawnEgg() : base("minecraft:guardian_spawn_egg") { }
	} // class

	public partial class ItemGusterBannerPattern : Item // minecraft:guster_banner_pattern
	{
		public ItemGusterBannerPattern() : base("minecraft:guster_banner_pattern") { }
	} // class

	public partial class ItemGusterPotterySherd : Item // minecraft:guster_pottery_sherd
	{
		public ItemGusterPotterySherd() : base("minecraft:guster_pottery_sherd") { }
	} // class

	public partial class ItemHappyGhastSpawnEgg : Item // minecraft:happy_ghast_spawn_egg
	{
		public ItemHappyGhastSpawnEgg() : base("minecraft:happy_ghast_spawn_egg") { }
	} // class

	public partial class ItemHardStainedGlass : Item // minecraft:hard_stained_glass
	{
		public ItemHardStainedGlass() : base("minecraft:hard_stained_glass") { }
	} // class

	public partial class ItemHardStainedGlassPane : Item // minecraft:hard_stained_glass_pane
	{
		public ItemHardStainedGlassPane() : base("minecraft:hard_stained_glass_pane") { }
	} // class

	public partial class ItemHeartPotterySherd : Item // minecraft:heart_pottery_sherd
	{
		public ItemHeartPotterySherd() : base("minecraft:heart_pottery_sherd") { }
	} // class

	public partial class ItemHeartbreakPotterySherd : Item // minecraft:heartbreak_pottery_sherd
	{
		public ItemHeartbreakPotterySherd() : base("minecraft:heartbreak_pottery_sherd") { }
	} // class

	public partial class ItemHoglinSpawnEgg : Item // minecraft:hoglin_spawn_egg
	{
		public ItemHoglinSpawnEgg() : base("minecraft:hoglin_spawn_egg") { }
	} // class

	public partial class ItemHorseSpawnEgg : Item // minecraft:horse_spawn_egg
	{
		public ItemHorseSpawnEgg() : base("minecraft:horse_spawn_egg") { }
	} // class

	public partial class ItemHostArmorTrimSmithingTemplate : Item // minecraft:host_armor_trim_smithing_template
	{
		public ItemHostArmorTrimSmithingTemplate() : base("minecraft:host_armor_trim_smithing_template") { }
	} // class

	public partial class ItemHowlPotterySherd : Item // minecraft:howl_pottery_sherd
	{
		public ItemHowlPotterySherd() : base("minecraft:howl_pottery_sherd") { }
	} // class

	public partial class ItemHuskSpawnEgg : Item // minecraft:husk_spawn_egg
	{
		public ItemHuskSpawnEgg() : base("minecraft:husk_spawn_egg") { }
	} // class

	public partial class ItemInkSac : Item // minecraft:ink_sac
	{
		public ItemInkSac() : base("minecraft:ink_sac") { }
	} // class

	public partial class ItemIronGolemSpawnEgg : Item // minecraft:iron_golem_spawn_egg
	{
		public ItemIronGolemSpawnEgg() : base("minecraft:iron_golem_spawn_egg") { }
	} // class

	public partial class ItemIronNautilusArmor : Item // minecraft:iron_nautilus_armor
	{
		public ItemIronNautilusArmor() : base("minecraft:iron_nautilus_armor") { }
	} // class

	public partial class ItemIronSpear : Item // minecraft:iron_spear
	{
		public ItemIronSpear() : base("minecraft:iron_spear") { }
	} // class

	public partial class ItemJungleBoat : Item // minecraft:jungle_boat
	{
		public ItemJungleBoat() : base("minecraft:jungle_boat") { }
	} // class

	public partial class ItemJungleChestBoat : Item // minecraft:jungle_chest_boat
	{
		public ItemJungleChestBoat() : base("minecraft:jungle_chest_boat") { }
	} // class

	public partial class ItemLapisLazuli : Item // minecraft:lapis_lazuli
	{
		public ItemLapisLazuli() : base("minecraft:lapis_lazuli") { }
	} // class

	public partial class ItemLavaBucket : Item // minecraft:lava_bucket
	{
		public ItemLavaBucket() : base("minecraft:lava_bucket") { }
	} // class

	public partial class ItemLeaves : Item // minecraft:leaves
	{
		public ItemLeaves() : base("minecraft:leaves") { }
	} // class

	public partial class ItemLeaves2 : Item // minecraft:leaves2
	{
		public ItemLeaves2() : base("minecraft:leaves2") { }
	} // class

	public partial class ItemLightBlock : Item // minecraft:light_block
	{
		public ItemLightBlock() : base("minecraft:light_block") { }
	} // class

	public partial class ItemLightBlueBundle : Item // minecraft:light_blue_bundle
	{
		public ItemLightBlueBundle() : base("minecraft:light_blue_bundle") { }
	} // class

	public partial class ItemLightBlueCushion : Item // minecraft:light_blue_cushion
	{
		public ItemLightBlueCushion() : base("minecraft:light_blue_cushion") { }
	} // class

	public partial class ItemLightBlueDye : Item // minecraft:light_blue_dye
	{
		public ItemLightBlueDye() : base("minecraft:light_blue_dye") { }
	} // class

	public partial class ItemLightBlueHarness : Item // minecraft:light_blue_harness
	{
		public ItemLightBlueHarness() : base("minecraft:light_blue_harness") { }
	} // class

	public partial class ItemLightGrayBundle : Item // minecraft:light_gray_bundle
	{
		public ItemLightGrayBundle() : base("minecraft:light_gray_bundle") { }
	} // class

	public partial class ItemLightGrayCushion : Item // minecraft:light_gray_cushion
	{
		public ItemLightGrayCushion() : base("minecraft:light_gray_cushion") { }
	} // class

	public partial class ItemLightGrayDye : Item // minecraft:light_gray_dye
	{
		public ItemLightGrayDye() : base("minecraft:light_gray_dye") { }
	} // class

	public partial class ItemLightGrayHarness : Item // minecraft:light_gray_harness
	{
		public ItemLightGrayHarness() : base("minecraft:light_gray_harness") { }
	} // class

	public partial class ItemLimeBundle : Item // minecraft:lime_bundle
	{
		public ItemLimeBundle() : base("minecraft:lime_bundle") { }
	} // class

	public partial class ItemLimeCushion : Item // minecraft:lime_cushion
	{
		public ItemLimeCushion() : base("minecraft:lime_cushion") { }
	} // class

	public partial class ItemLimeDye : Item // minecraft:lime_dye
	{
		public ItemLimeDye() : base("minecraft:lime_dye") { }
	} // class

	public partial class ItemLimeHarness : Item // minecraft:lime_harness
	{
		public ItemLimeHarness() : base("minecraft:lime_harness") { }
	} // class

	public partial class ItemLlamaSpawnEgg : Item // minecraft:llama_spawn_egg
	{
		public ItemLlamaSpawnEgg() : base("minecraft:llama_spawn_egg") { }
	} // class

	public partial class ItemLog : Item // minecraft:log
	{
		public ItemLog() : base("minecraft:log") { }
	} // class

	public partial class ItemLog2 : Item // minecraft:log2
	{
		public ItemLog2() : base("minecraft:log2") { }
	} // class

	public partial class ItemMace : Item // minecraft:mace
	{
		public ItemMace() : base("minecraft:mace") { }
	} // class

	public partial class ItemMagentaBundle : Item // minecraft:magenta_bundle
	{
		public ItemMagentaBundle() : base("minecraft:magenta_bundle") { }
	} // class

	public partial class ItemMagentaCushion : Item // minecraft:magenta_cushion
	{
		public ItemMagentaCushion() : base("minecraft:magenta_cushion") { }
	} // class

	public partial class ItemMagentaDye : Item // minecraft:magenta_dye
	{
		public ItemMagentaDye() : base("minecraft:magenta_dye") { }
	} // class

	public partial class ItemMagentaHarness : Item // minecraft:magenta_harness
	{
		public ItemMagentaHarness() : base("minecraft:magenta_harness") { }
	} // class

	public partial class ItemMagmaCubeSpawnEgg : Item // minecraft:magma_cube_spawn_egg
	{
		public ItemMagmaCubeSpawnEgg() : base("minecraft:magma_cube_spawn_egg") { }
	} // class

	public partial class ItemMangroveBoat : Item // minecraft:mangrove_boat
	{
		public ItemMangroveBoat() : base("minecraft:mangrove_boat") { }
	} // class

	public partial class ItemMangroveChestBoat : Item // minecraft:mangrove_chest_boat
	{
		public ItemMangroveChestBoat() : base("minecraft:mangrove_chest_boat") { }
	} // class

	public partial class ItemMangroveSign : Item // minecraft:mangrove_sign
	{
		public ItemMangroveSign() : base("minecraft:mangrove_sign") { }
	} // class

	public partial class ItemMilkBucket : Item // minecraft:milk_bucket
	{
		public ItemMilkBucket() : base("minecraft:milk_bucket") { }
	} // class

	public partial class ItemMinerPotterySherd : Item // minecraft:miner_pottery_sherd
	{
		public ItemMinerPotterySherd() : base("minecraft:miner_pottery_sherd") { }
	} // class

	public partial class ItemMojangBannerPattern : Item // minecraft:mojang_banner_pattern
	{
		public ItemMojangBannerPattern() : base("minecraft:mojang_banner_pattern") { }
	} // class

	public partial class ItemMonsterEgg : Item // minecraft:monster_egg
	{
		public ItemMonsterEgg() : base("minecraft:monster_egg") { }
	} // class

	public partial class ItemMooshroomSpawnEgg : Item // minecraft:mooshroom_spawn_egg
	{
		public ItemMooshroomSpawnEgg() : base("minecraft:mooshroom_spawn_egg") { }
	} // class

	public partial class ItemMournerPotterySherd : Item // minecraft:mourner_pottery_sherd
	{
		public ItemMournerPotterySherd() : base("minecraft:mourner_pottery_sherd") { }
	} // class

	public partial class ItemMuleSpawnEgg : Item // minecraft:mule_spawn_egg
	{
		public ItemMuleSpawnEgg() : base("minecraft:mule_spawn_egg") { }
	} // class

	public partial class ItemMusicDisc5 : Item // minecraft:music_disc_5
	{
		public ItemMusicDisc5() : base("minecraft:music_disc_5") { }
	} // class

	public partial class ItemMusicDiscBounce : Item // minecraft:music_disc_bounce
	{
		public ItemMusicDiscBounce() : base("minecraft:music_disc_bounce") { }
	} // class

	public partial class ItemMusicDiscCreator : Item // minecraft:music_disc_creator
	{
		public ItemMusicDiscCreator() : base("minecraft:music_disc_creator") { }
	} // class

	public partial class ItemMusicDiscCreatorMusicBox : Item // minecraft:music_disc_creator_music_box
	{
		public ItemMusicDiscCreatorMusicBox() : base("minecraft:music_disc_creator_music_box") { }
	} // class

	public partial class ItemMusicDiscLavaChicken : Item // minecraft:music_disc_lava_chicken
	{
		public ItemMusicDiscLavaChicken() : base("minecraft:music_disc_lava_chicken") { }
	} // class

	public partial class ItemMusicDiscOtherside : Item // minecraft:music_disc_otherside
	{
		public ItemMusicDiscOtherside() : base("minecraft:music_disc_otherside") { }
	} // class

	public partial class ItemMusicDiscPrecipice : Item // minecraft:music_disc_precipice
	{
		public ItemMusicDiscPrecipice() : base("minecraft:music_disc_precipice") { }
	} // class

	public partial class ItemMusicDiscRelic : Item // minecraft:music_disc_relic
	{
		public ItemMusicDiscRelic() : base("minecraft:music_disc_relic") { }
	} // class

	public partial class ItemMusicDiscTears : Item // minecraft:music_disc_tears
	{
		public ItemMusicDiscTears() : base("minecraft:music_disc_tears") { }
	} // class

	public partial class ItemMutton : Item // minecraft:mutton
	{
		public ItemMutton() : base("minecraft:mutton") { }
	} // class

	public partial class ItemNautilusSpawnEgg : Item // minecraft:nautilus_spawn_egg
	{
		public ItemNautilusSpawnEgg() : base("minecraft:nautilus_spawn_egg") { }
	} // class

	public partial class ItemNetheriteHorseArmor : Item // minecraft:netherite_horse_armor
	{
		public ItemNetheriteHorseArmor() : base("minecraft:netherite_horse_armor") { }
	} // class

	public partial class ItemNetheriteNautilusArmor : Item // minecraft:netherite_nautilus_armor
	{
		public ItemNetheriteNautilusArmor() : base("minecraft:netherite_nautilus_armor") { }
	} // class

	public partial class ItemNetheriteSpear : Item // minecraft:netherite_spear
	{
		public ItemNetheriteSpear() : base("minecraft:netherite_spear") { }
	} // class

	public partial class ItemNetheriteUpgradeSmithingTemplate : Item // minecraft:netherite_upgrade_smithing_template
	{
		public ItemNetheriteUpgradeSmithingTemplate() : base("minecraft:netherite_upgrade_smithing_template") { }
	} // class

	public partial class ItemNpcSpawnEgg : Item // minecraft:npc_spawn_egg
	{
		public ItemNpcSpawnEgg() : base("minecraft:npc_spawn_egg") { }
	} // class

	public partial class ItemOakBoat : Item // minecraft:oak_boat
	{
		public ItemOakBoat() : base("minecraft:oak_boat") { }
	} // class

	public partial class ItemOakChestBoat : Item // minecraft:oak_chest_boat
	{
		public ItemOakChestBoat() : base("minecraft:oak_chest_boat") { }
	} // class

	public partial class ItemOcelotSpawnEgg : Item // minecraft:ocelot_spawn_egg
	{
		public ItemOcelotSpawnEgg() : base("minecraft:ocelot_spawn_egg") { }
	} // class

	public partial class ItemOminousBottle : Item // minecraft:ominous_bottle
	{
		public ItemOminousBottle() : base("minecraft:ominous_bottle") { }
	} // class

	public partial class ItemOminousTrialKey : Item // minecraft:ominous_trial_key
	{
		public ItemOminousTrialKey() : base("minecraft:ominous_trial_key") { }
	} // class

	public partial class ItemOrangeBundle : Item // minecraft:orange_bundle
	{
		public ItemOrangeBundle() : base("minecraft:orange_bundle") { }
	} // class

	public partial class ItemOrangeCushion : Item // minecraft:orange_cushion
	{
		public ItemOrangeCushion() : base("minecraft:orange_cushion") { }
	} // class

	public partial class ItemOrangeDye : Item // minecraft:orange_dye
	{
		public ItemOrangeDye() : base("minecraft:orange_dye") { }
	} // class

	public partial class ItemOrangeHarness : Item // minecraft:orange_harness
	{
		public ItemOrangeHarness() : base("minecraft:orange_harness") { }
	} // class

	public partial class ItemPaleOakBoat : Item // minecraft:pale_oak_boat
	{
		public ItemPaleOakBoat() : base("minecraft:pale_oak_boat") { }
	} // class

	public partial class ItemPaleOakChestBoat : Item // minecraft:pale_oak_chest_boat
	{
		public ItemPaleOakChestBoat() : base("minecraft:pale_oak_chest_boat") { }
	} // class

	public partial class ItemPaleOakSign : Item // minecraft:pale_oak_sign
	{
		public ItemPaleOakSign() : base("minecraft:pale_oak_sign") { }
	} // class

	public partial class ItemPandaSpawnEgg : Item // minecraft:panda_spawn_egg
	{
		public ItemPandaSpawnEgg() : base("minecraft:panda_spawn_egg") { }
	} // class

	public partial class ItemParchedSpawnEgg : Item // minecraft:parched_spawn_egg
	{
		public ItemParchedSpawnEgg() : base("minecraft:parched_spawn_egg") { }
	} // class

	public partial class ItemParrotSpawnEgg : Item // minecraft:parrot_spawn_egg
	{
		public ItemParrotSpawnEgg() : base("minecraft:parrot_spawn_egg") { }
	} // class

	public partial class ItemPhantomSpawnEgg : Item // minecraft:phantom_spawn_egg
	{
		public ItemPhantomSpawnEgg() : base("minecraft:phantom_spawn_egg") { }
	} // class

	public partial class ItemPhotoItem : Item // minecraft:photo_item
	{
		public ItemPhotoItem() : base("minecraft:photo_item") { }
	} // class

	public partial class ItemPigSpawnEgg : Item // minecraft:pig_spawn_egg
	{
		public ItemPigSpawnEgg() : base("minecraft:pig_spawn_egg") { }
	} // class

	public partial class ItemPiglinBannerPattern : Item // minecraft:piglin_banner_pattern
	{
		public ItemPiglinBannerPattern() : base("minecraft:piglin_banner_pattern") { }
	} // class

	public partial class ItemPiglinBruteSpawnEgg : Item // minecraft:piglin_brute_spawn_egg
	{
		public ItemPiglinBruteSpawnEgg() : base("minecraft:piglin_brute_spawn_egg") { }
	} // class

	public partial class ItemPiglinSpawnEgg : Item // minecraft:piglin_spawn_egg
	{
		public ItemPiglinSpawnEgg() : base("minecraft:piglin_spawn_egg") { }
	} // class

	public partial class ItemPillagerSpawnEgg : Item // minecraft:pillager_spawn_egg
	{
		public ItemPillagerSpawnEgg() : base("minecraft:pillager_spawn_egg") { }
	} // class

	public partial class ItemPinkBundle : Item // minecraft:pink_bundle
	{
		public ItemPinkBundle() : base("minecraft:pink_bundle") { }
	} // class

	public partial class ItemPinkCushion : Item // minecraft:pink_cushion
	{
		public ItemPinkCushion() : base("minecraft:pink_cushion") { }
	} // class

	public partial class ItemPinkDye : Item // minecraft:pink_dye
	{
		public ItemPinkDye() : base("minecraft:pink_dye") { }
	} // class

	public partial class ItemPinkHarness : Item // minecraft:pink_harness
	{
		public ItemPinkHarness() : base("minecraft:pink_harness") { }
	} // class

	public partial class ItemPitcherPod : Item // minecraft:pitcher_pod
	{
		public ItemPitcherPod() : base("minecraft:pitcher_pod") { }
	} // class

	public partial class ItemPlanks : Item // minecraft:planks
	{
		public ItemPlanks() : base("minecraft:planks") { }
	} // class

	public partial class ItemPlentyPotterySherd : Item // minecraft:plenty_pottery_sherd
	{
		public ItemPlentyPotterySherd() : base("minecraft:plenty_pottery_sherd") { }
	} // class

	public partial class ItemPolarBearSpawnEgg : Item // minecraft:polar_bear_spawn_egg
	{
		public ItemPolarBearSpawnEgg() : base("minecraft:polar_bear_spawn_egg") { }
	} // class

	public partial class ItemPoplarBoat : Item // minecraft:poplar_boat
	{
		public ItemPoplarBoat() : base("minecraft:poplar_boat") { }
	} // class

	public partial class ItemPoplarChestBoat : Item // minecraft:poplar_chest_boat
	{
		public ItemPoplarChestBoat() : base("minecraft:poplar_chest_boat") { }
	} // class

	public partial class ItemPoplarSign : Item // minecraft:poplar_sign
	{
		public ItemPoplarSign() : base("minecraft:poplar_sign") { }
	} // class

	public partial class ItemPortfolio : Item // minecraft:portfolio
	{
		public ItemPortfolio() : base("minecraft:portfolio") { }
	} // class

	public partial class ItemPowderSnowBucket : Item // minecraft:powder_snow_bucket
	{
		public ItemPowderSnowBucket() : base("minecraft:powder_snow_bucket") { }
	} // class

	public partial class ItemPrizePotterySherd : Item // minecraft:prize_pottery_sherd
	{
		public ItemPrizePotterySherd() : base("minecraft:prize_pottery_sherd") { }
	} // class

	public partial class ItemPufferfishBucket : Item // minecraft:pufferfish_bucket
	{
		public ItemPufferfishBucket() : base("minecraft:pufferfish_bucket") { }
	} // class

	public partial class ItemPufferfishSpawnEgg : Item // minecraft:pufferfish_spawn_egg
	{
		public ItemPufferfishSpawnEgg() : base("minecraft:pufferfish_spawn_egg") { }
	} // class

	public partial class ItemPurpleBundle : Item // minecraft:purple_bundle
	{
		public ItemPurpleBundle() : base("minecraft:purple_bundle") { }
	} // class

	public partial class ItemPurpleCushion : Item // minecraft:purple_cushion
	{
		public ItemPurpleCushion() : base("minecraft:purple_cushion") { }
	} // class

	public partial class ItemPurpleDye : Item // minecraft:purple_dye
	{
		public ItemPurpleDye() : base("minecraft:purple_dye") { }
	} // class

	public partial class ItemPurpleHarness : Item // minecraft:purple_harness
	{
		public ItemPurpleHarness() : base("minecraft:purple_harness") { }
	} // class

	public partial class ItemRabbitSpawnEgg : Item // minecraft:rabbit_spawn_egg
	{
		public ItemRabbitSpawnEgg() : base("minecraft:rabbit_spawn_egg") { }
	} // class

	public partial class ItemRaiserArmorTrimSmithingTemplate : Item // minecraft:raiser_armor_trim_smithing_template
	{
		public ItemRaiserArmorTrimSmithingTemplate() : base("minecraft:raiser_armor_trim_smithing_template") { }
	} // class

	public partial class ItemRavagerSpawnEgg : Item // minecraft:ravager_spawn_egg
	{
		public ItemRavagerSpawnEgg() : base("minecraft:ravager_spawn_egg") { }
	} // class

	public partial class ItemRawCopper : Item // minecraft:raw_copper
	{
		public ItemRawCopper() : base("minecraft:raw_copper") { }
	} // class

	public partial class ItemRawGold : Item // minecraft:raw_gold
	{
		public ItemRawGold() : base("minecraft:raw_gold") { }
	} // class

	public partial class ItemRawIron : Item // minecraft:raw_iron
	{
		public ItemRawIron() : base("minecraft:raw_iron") { }
	} // class

	public partial class ItemRecoveryCompass : Item // minecraft:recovery_compass
	{
		public ItemRecoveryCompass() : base("minecraft:recovery_compass") { }
	} // class

	public partial class ItemRedBundle : Item // minecraft:red_bundle
	{
		public ItemRedBundle() : base("minecraft:red_bundle") { }
	} // class

	public partial class ItemRedCushion : Item // minecraft:red_cushion
	{
		public ItemRedCushion() : base("minecraft:red_cushion") { }
	} // class

	public partial class ItemRedDye : Item // minecraft:red_dye
	{
		public ItemRedDye() : base("minecraft:red_dye") { }
	} // class

	public partial class ItemRedFlower : Item // minecraft:red_flower
	{
		public ItemRedFlower() : base("minecraft:red_flower") { }
	} // class

	public partial class ItemRedHarness : Item // minecraft:red_harness
	{
		public ItemRedHarness() : base("minecraft:red_harness") { }
	} // class

	public partial class ItemResinBrick : Item // minecraft:resin_brick
	{
		public ItemResinBrick() : base("minecraft:resin_brick") { }
	} // class

	public partial class ItemRibArmorTrimSmithingTemplate : Item // minecraft:rib_armor_trim_smithing_template
	{
		public ItemRibArmorTrimSmithingTemplate() : base("minecraft:rib_armor_trim_smithing_template") { }
	} // class

	public partial class ItemSalmonBucket : Item // minecraft:salmon_bucket
	{
		public ItemSalmonBucket() : base("minecraft:salmon_bucket") { }
	} // class

	public partial class ItemSalmonSpawnEgg : Item // minecraft:salmon_spawn_egg
	{
		public ItemSalmonSpawnEgg() : base("minecraft:salmon_spawn_egg") { }
	} // class

	public partial class ItemSapling : Item // minecraft:sapling
	{
		public ItemSapling() : base("minecraft:sapling") { }
	} // class

	public partial class ItemScrapePotterySherd : Item // minecraft:scrape_pottery_sherd
	{
		public ItemScrapePotterySherd() : base("minecraft:scrape_pottery_sherd") { }
	} // class

	public partial class ItemSentryArmorTrimSmithingTemplate : Item // minecraft:sentry_armor_trim_smithing_template
	{
		public ItemSentryArmorTrimSmithingTemplate() : base("minecraft:sentry_armor_trim_smithing_template") { }
	} // class

	public partial class ItemShaperArmorTrimSmithingTemplate : Item // minecraft:shaper_armor_trim_smithing_template
	{
		public ItemShaperArmorTrimSmithingTemplate() : base("minecraft:shaper_armor_trim_smithing_template") { }
	} // class

	public partial class ItemSheafPotterySherd : Item // minecraft:sheaf_pottery_sherd
	{
		public ItemSheafPotterySherd() : base("minecraft:sheaf_pottery_sherd") { }
	} // class

	public partial class ItemSheepSpawnEgg : Item // minecraft:sheep_spawn_egg
	{
		public ItemSheepSpawnEgg() : base("minecraft:sheep_spawn_egg") { }
	} // class

	public partial class ItemShelterPotterySherd : Item // minecraft:shelter_pottery_sherd
	{
		public ItemShelterPotterySherd() : base("minecraft:shelter_pottery_sherd") { }
	} // class

	public partial class ItemShulkerBox : Item // minecraft:shulker_box
	{
		public ItemShulkerBox() : base("minecraft:shulker_box") { }
	} // class

	public partial class ItemShulkerSpawnEgg : Item // minecraft:shulker_spawn_egg
	{
		public ItemShulkerSpawnEgg() : base("minecraft:shulker_spawn_egg") { }
	} // class

	public partial class ItemSilenceArmorTrimSmithingTemplate : Item // minecraft:silence_armor_trim_smithing_template
	{
		public ItemSilenceArmorTrimSmithingTemplate() : base("minecraft:silence_armor_trim_smithing_template") { }
	} // class

	public partial class ItemSilverfishSpawnEgg : Item // minecraft:silverfish_spawn_egg
	{
		public ItemSilverfishSpawnEgg() : base("minecraft:silverfish_spawn_egg") { }
	} // class

	public partial class ItemSkeletonHorseSpawnEgg : Item // minecraft:skeleton_horse_spawn_egg
	{
		public ItemSkeletonHorseSpawnEgg() : base("minecraft:skeleton_horse_spawn_egg") { }
	} // class

	public partial class ItemSkeletonSpawnEgg : Item // minecraft:skeleton_spawn_egg
	{
		public ItemSkeletonSpawnEgg() : base("minecraft:skeleton_spawn_egg") { }
	} // class

	public partial class ItemSkullBannerPattern : Item // minecraft:skull_banner_pattern
	{
		public ItemSkullBannerPattern() : base("minecraft:skull_banner_pattern") { }
	} // class

	public partial class ItemSkullPotterySherd : Item // minecraft:skull_pottery_sherd
	{
		public ItemSkullPotterySherd() : base("minecraft:skull_pottery_sherd") { }
	} // class

	public partial class ItemSlimeSpawnEgg : Item // minecraft:slime_spawn_egg
	{
		public ItemSlimeSpawnEgg() : base("minecraft:slime_spawn_egg") { }
	} // class

	public partial class ItemSnifferSpawnEgg : Item // minecraft:sniffer_spawn_egg
	{
		public ItemSnifferSpawnEgg() : base("minecraft:sniffer_spawn_egg") { }
	} // class

	public partial class ItemSnortPotterySherd : Item // minecraft:snort_pottery_sherd
	{
		public ItemSnortPotterySherd() : base("minecraft:snort_pottery_sherd") { }
	} // class

	public partial class ItemSnoutArmorTrimSmithingTemplate : Item // minecraft:snout_armor_trim_smithing_template
	{
		public ItemSnoutArmorTrimSmithingTemplate() : base("minecraft:snout_armor_trim_smithing_template") { }
	} // class

	public partial class ItemSnowGolemSpawnEgg : Item // minecraft:snow_golem_spawn_egg
	{
		public ItemSnowGolemSpawnEgg() : base("minecraft:snow_golem_spawn_egg") { }
	} // class

	public partial class ItemSpiderSpawnEgg : Item // minecraft:spider_spawn_egg
	{
		public ItemSpiderSpawnEgg() : base("minecraft:spider_spawn_egg") { }
	} // class

	public partial class ItemSpireArmorTrimSmithingTemplate : Item // minecraft:spire_armor_trim_smithing_template
	{
		public ItemSpireArmorTrimSmithingTemplate() : base("minecraft:spire_armor_trim_smithing_template") { }
	} // class

	public partial class ItemSpruceBoat : Item // minecraft:spruce_boat
	{
		public ItemSpruceBoat() : base("minecraft:spruce_boat") { }
	} // class

	public partial class ItemSpruceChestBoat : Item // minecraft:spruce_chest_boat
	{
		public ItemSpruceChestBoat() : base("minecraft:spruce_chest_boat") { }
	} // class

	public partial class ItemSpyglass : Item // minecraft:spyglass
	{
		public ItemSpyglass() : base("minecraft:spyglass") { }
	} // class

	public partial class ItemSquidSpawnEgg : Item // minecraft:squid_spawn_egg
	{
		public ItemSquidSpawnEgg() : base("minecraft:squid_spawn_egg") { }
	} // class

	public partial class ItemStainedGlass : Item // minecraft:stained_glass
	{
		public ItemStainedGlass() : base("minecraft:stained_glass") { }
	} // class

	public partial class ItemStainedGlassPane : Item // minecraft:stained_glass_pane
	{
		public ItemStainedGlassPane() : base("minecraft:stained_glass_pane") { }
	} // class

	public partial class ItemStainedHardenedClay : Item // minecraft:stained_hardened_clay
	{
		public ItemStainedHardenedClay() : base("minecraft:stained_hardened_clay") { }
	} // class

	public partial class ItemStoneBlockSlab : Item // minecraft:stone_block_slab
	{
		public ItemStoneBlockSlab() : base("minecraft:stone_block_slab") { }
	} // class

	public partial class ItemStoneBlockSlab2 : Item // minecraft:stone_block_slab2
	{
		public ItemStoneBlockSlab2() : base("minecraft:stone_block_slab2") { }
	} // class

	public partial class ItemStoneBlockSlab3 : Item // minecraft:stone_block_slab3
	{
		public ItemStoneBlockSlab3() : base("minecraft:stone_block_slab3") { }
	} // class

	public partial class ItemStoneBlockSlab4 : Item // minecraft:stone_block_slab4
	{
		public ItemStoneBlockSlab4() : base("minecraft:stone_block_slab4") { }
	} // class

	public partial class ItemStoneSpear : Item // minecraft:stone_spear
	{
		public ItemStoneSpear() : base("minecraft:stone_spear") { }
	} // class

	public partial class ItemStonebrick : Item // minecraft:stonebrick
	{
		public ItemStonebrick() : base("minecraft:stonebrick") { }
	} // class

	public partial class ItemStraySpawnEgg : Item // minecraft:stray_spawn_egg
	{
		public ItemStraySpawnEgg() : base("minecraft:stray_spawn_egg") { }
	} // class

	public partial class ItemStriderSpawnEgg : Item // minecraft:strider_spawn_egg
	{
		public ItemStriderSpawnEgg() : base("minecraft:strider_spawn_egg") { }
	} // class

	public partial class ItemSulfurCubeBucket : Item // minecraft:sulfur_cube_bucket
	{
		public ItemSulfurCubeBucket() : base("minecraft:sulfur_cube_bucket") { }
	} // class

	public partial class ItemSulfurCubeSpawnEgg : Item // minecraft:sulfur_cube_spawn_egg
	{
		public ItemSulfurCubeSpawnEgg() : base("minecraft:sulfur_cube_spawn_egg") { }
	} // class

	public partial class ItemTadpoleBucket : Item // minecraft:tadpole_bucket
	{
		public ItemTadpoleBucket() : base("minecraft:tadpole_bucket") { }
	} // class

	public partial class ItemTadpoleSpawnEgg : Item // minecraft:tadpole_spawn_egg
	{
		public ItemTadpoleSpawnEgg() : base("minecraft:tadpole_spawn_egg") { }
	} // class

	public partial class ItemTallgrass : Item // minecraft:tallgrass
	{
		public ItemTallgrass() : base("minecraft:tallgrass") { }
	} // class

	public partial class ItemTideArmorTrimSmithingTemplate : Item // minecraft:tide_armor_trim_smithing_template
	{
		public ItemTideArmorTrimSmithingTemplate() : base("minecraft:tide_armor_trim_smithing_template") { }
	} // class

	public partial class ItemTorchflowerSeeds : Item // minecraft:torchflower_seeds
	{
		public ItemTorchflowerSeeds() : base("minecraft:torchflower_seeds") { }
	} // class

	public partial class ItemTraderLlamaSpawnEgg : Item // minecraft:trader_llama_spawn_egg
	{
		public ItemTraderLlamaSpawnEgg() : base("minecraft:trader_llama_spawn_egg") { }
	} // class

	public partial class ItemTrialKey : Item // minecraft:trial_key
	{
		public ItemTrialKey() : base("minecraft:trial_key") { }
	} // class

	public partial class ItemTropicalFishBucket : Item // minecraft:tropical_fish_bucket
	{
		public ItemTropicalFishBucket() : base("minecraft:tropical_fish_bucket") { }
	} // class

	public partial class ItemTropicalFishSpawnEgg : Item // minecraft:tropical_fish_spawn_egg
	{
		public ItemTropicalFishSpawnEgg() : base("minecraft:tropical_fish_spawn_egg") { }
	} // class

	public partial class ItemTurtleSpawnEgg : Item // minecraft:turtle_spawn_egg
	{
		public ItemTurtleSpawnEgg() : base("minecraft:turtle_spawn_egg") { }
	} // class

	public partial class ItemVexArmorTrimSmithingTemplate : Item // minecraft:vex_armor_trim_smithing_template
	{
		public ItemVexArmorTrimSmithingTemplate() : base("minecraft:vex_armor_trim_smithing_template") { }
	} // class

	public partial class ItemVexSpawnEgg : Item // minecraft:vex_spawn_egg
	{
		public ItemVexSpawnEgg() : base("minecraft:vex_spawn_egg") { }
	} // class

	public partial class ItemVillagerSpawnEgg : Item // minecraft:villager_spawn_egg
	{
		public ItemVillagerSpawnEgg() : base("minecraft:villager_spawn_egg") { }
	} // class

	public partial class ItemVindicatorSpawnEgg : Item // minecraft:vindicator_spawn_egg
	{
		public ItemVindicatorSpawnEgg() : base("minecraft:vindicator_spawn_egg") { }
	} // class

	public partial class ItemWanderingTraderSpawnEgg : Item // minecraft:wandering_trader_spawn_egg
	{
		public ItemWanderingTraderSpawnEgg() : base("minecraft:wandering_trader_spawn_egg") { }
	} // class

	public partial class ItemWardArmorTrimSmithingTemplate : Item // minecraft:ward_armor_trim_smithing_template
	{
		public ItemWardArmorTrimSmithingTemplate() : base("minecraft:ward_armor_trim_smithing_template") { }
	} // class

	public partial class ItemWardenSpawnEgg : Item // minecraft:warden_spawn_egg
	{
		public ItemWardenSpawnEgg() : base("minecraft:warden_spawn_egg") { }
	} // class

	public partial class ItemWaterBucket : Item // minecraft:water_bucket
	{
		public ItemWaterBucket() : base("minecraft:water_bucket") { }
	} // class

	public partial class ItemWayfinderArmorTrimSmithingTemplate : Item // minecraft:wayfinder_armor_trim_smithing_template
	{
		public ItemWayfinderArmorTrimSmithingTemplate() : base("minecraft:wayfinder_armor_trim_smithing_template") { }
	} // class

	public partial class ItemWhiteBundle : Item // minecraft:white_bundle
	{
		public ItemWhiteBundle() : base("minecraft:white_bundle") { }
	} // class

	public partial class ItemWhiteCushion : Item // minecraft:white_cushion
	{
		public ItemWhiteCushion() : base("minecraft:white_cushion") { }
	} // class

	public partial class ItemWhiteDye : Item // minecraft:white_dye
	{
		public ItemWhiteDye() : base("minecraft:white_dye") { }
	} // class

	public partial class ItemWhiteHarness : Item // minecraft:white_harness
	{
		public ItemWhiteHarness() : base("minecraft:white_harness") { }
	} // class

	public partial class ItemWildArmorTrimSmithingTemplate : Item // minecraft:wild_armor_trim_smithing_template
	{
		public ItemWildArmorTrimSmithingTemplate() : base("minecraft:wild_armor_trim_smithing_template") { }
	} // class

	public partial class ItemWindCharge : Item // minecraft:wind_charge
	{
		public ItemWindCharge() : base("minecraft:wind_charge") { }
	} // class

	public partial class ItemWitchSpawnEgg : Item // minecraft:witch_spawn_egg
	{
		public ItemWitchSpawnEgg() : base("minecraft:witch_spawn_egg") { }
	} // class

	public partial class ItemWitherSkeletonSpawnEgg : Item // minecraft:wither_skeleton_spawn_egg
	{
		public ItemWitherSkeletonSpawnEgg() : base("minecraft:wither_skeleton_spawn_egg") { }
	} // class

	public partial class ItemWitherSpawnEgg : Item // minecraft:wither_spawn_egg
	{
		public ItemWitherSpawnEgg() : base("minecraft:wither_spawn_egg") { }
	} // class

	public partial class ItemWolfArmor : Item // minecraft:wolf_armor
	{
		public ItemWolfArmor() : base("minecraft:wolf_armor") { }
	} // class

	public partial class ItemWolfSpawnEgg : Item // minecraft:wolf_spawn_egg
	{
		public ItemWolfSpawnEgg() : base("minecraft:wolf_spawn_egg") { }
	} // class

	public partial class ItemWood : Item // minecraft:wood
	{
		public ItemWood() : base("minecraft:wood") { }
	} // class

	public partial class ItemWoodenSlab : Item // minecraft:wooden_slab
	{
		public ItemWoodenSlab() : base("minecraft:wooden_slab") { }
	} // class

	public partial class ItemWoodenSpear : Item // minecraft:wooden_spear
	{
		public ItemWoodenSpear() : base("minecraft:wooden_spear") { }
	} // class

	public partial class ItemWool : Item // minecraft:wool
	{
		public ItemWool() : base("minecraft:wool") { }
	} // class

	public partial class ItemYellowBundle : Item // minecraft:yellow_bundle
	{
		public ItemYellowBundle() : base("minecraft:yellow_bundle") { }
	} // class

	public partial class ItemYellowCushion : Item // minecraft:yellow_cushion
	{
		public ItemYellowCushion() : base("minecraft:yellow_cushion") { }
	} // class

	public partial class ItemYellowDye : Item // minecraft:yellow_dye
	{
		public ItemYellowDye() : base("minecraft:yellow_dye") { }
	} // class

	public partial class ItemYellowHarness : Item // minecraft:yellow_harness
	{
		public ItemYellowHarness() : base("minecraft:yellow_harness") { }
	} // class

	public partial class ItemZoglinSpawnEgg : Item // minecraft:zoglin_spawn_egg
	{
		public ItemZoglinSpawnEgg() : base("minecraft:zoglin_spawn_egg") { }
	} // class

	public partial class ItemZombieHorseSpawnEgg : Item // minecraft:zombie_horse_spawn_egg
	{
		public ItemZombieHorseSpawnEgg() : base("minecraft:zombie_horse_spawn_egg") { }
	} // class

	public partial class ItemZombieNautilusSpawnEgg : Item // minecraft:zombie_nautilus_spawn_egg
	{
		public ItemZombieNautilusSpawnEgg() : base("minecraft:zombie_nautilus_spawn_egg") { }
	} // class

	public partial class ItemZombiePigmanSpawnEgg : Item // minecraft:zombie_pigman_spawn_egg
	{
		public ItemZombiePigmanSpawnEgg() : base("minecraft:zombie_pigman_spawn_egg") { }
	} // class

	public partial class ItemZombieSpawnEgg : Item // minecraft:zombie_spawn_egg
	{
		public ItemZombieSpawnEgg() : base("minecraft:zombie_spawn_egg") { }
	} // class

	public partial class ItemZombieVillagerSpawnEgg : Item // minecraft:zombie_villager_spawn_egg
	{
		public ItemZombieVillagerSpawnEgg() : base("minecraft:zombie_villager_spawn_egg") { }
	} // class
}
