#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
//
// The Original Code is MiNET.
//
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
//
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2020 Niclas Olofsson.
// All Rights Reserved.

#endregion

using System.Globalization;
using System.Text;

namespace MiNET.ProtocolGen;

public static class GeneratedFile
{
	public const string LicenseHeader = """
		#region LICENSE

		// The contents of this file are subject to the Common Public Attribution
		// License Version 1.0. (the "License"); you may not use this file except in
		// compliance with the License. You may obtain a copy of the License at
		// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
		// The License is based on the Mozilla Public License Version 1.1, but Sections 14
		// and 15 have been added to cover use of software over a computer network and
		// provide for limited attribution for the Original Developer. In addition, Exhibit A has
		// been modified to be consistent with Exhibit B.
		//
		// Software distributed under the License is distributed on an "AS IS" basis,
		// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
		// the specific language governing rights and limitations under the License.
		//
		// The Original Code is MiNET.
		//
		// The Original Developer is the Initial Developer.  The Initial Developer of
		// the Original Code is Niclas Olofsson.
		//
		// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson.
		// All Rights Reserved.

		#endregion

		""";

	public static void Write(string path, StringBuilder content)
	{
		// Match the repo's generated-file conventions: UTF-8 with BOM, no final newline.
		File.WriteAllText(path, content.ToString().TrimEnd('\r', '\n'), new UTF8Encoding(true));
	}

	public static int IdValue(string id)
	{
		string hex = id.StartsWith("0x") ? id.Substring(2) : id;
		return int.Parse(hex, NumberStyles.HexNumber);
	}
}

/// <summary>
///     Emits MCPE Protocol Registry.cs: the handler interfaces, the client dispatcher and the
///     packet factory, covering the XML pdus and the Cereal roster together. The output is the
///     same code the T4 template emitted when it owned these blocks.
/// </summary>
public static class RegistryEmitter
{
	public static void Emit(string path, List<XmlPdu> xmlPdus, List<RosterEntry> roster)
	{
		// The XML is in id order; fold the roster packets in at their id positions so the
		// output reads as one protocol, not two lists. The interfaces and the dispatcher cover
		// everything except raknet (the T4 selectors only excluded raknet, so ftl is included);
		// the factory's mcpe switch covers the mcpe namespace only, ftl has its own switch.
		var mcpe = new List<(int idValue, string id, string typeName, bool client, bool server)>();
		var handled = new List<(int idValue, string id, string typeName, bool client, bool server)>();
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace != "raknet"))
		{
			var item = (GeneratedFile.IdValue(pdu.Id), pdu.Id, CodeNames.CodeTypeName(pdu.Name), pdu.Client, pdu.Server);
			handled.Add(item);
			if (pdu.Namespace != "ftl") mcpe.Add(item);
		}
		foreach (RosterEntry entry in roster)
		{
			var item = (GeneratedFile.IdValue(entry.Id), entry.Id, entry.TypeName, entry.Client, entry.Server);
			handled.Add(item);
			mcpe.Add(item);
		}
		mcpe.Sort((a, b) => a.idValue.CompareTo(b.idValue));
		handled.Sort((a, b) => a.idValue.CompareTo(b.idValue));

		var sb = new StringBuilder();
		sb.Append(GeneratedFile.LicenseHeader);
		sb.AppendLine();
		sb.AppendLine("//");
		sb.AppendLine("// WARNING: GENERATED CODE - DO NOT EDIT");
		sb.AppendLine("// Generated by MiNET.ProtocolGen from MCPE Protocol.xml and roster.json.");
		sb.AppendLine("//");
		sb.AppendLine();
		sb.AppendLine("using System;");
		sb.AppendLine();
		sb.AppendLine("namespace MiNET.Net");
		sb.AppendLine("{");

		sb.AppendLine("\tpublic interface IMcpeMessageHandler");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tvoid Disconnect(string reason, bool sendDisconnect = true);");
		sb.AppendLine();
		foreach (var p in handled.Where(p => p.client))
		{
			sb.AppendLine($"\t\tvoid Handle{p.typeName}({p.typeName} message);");
		}
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic interface IMcpeClientMessageHandler");
		sb.AppendLine("\t{");
		foreach (var p in handled.Where(p => p.server))
		{
			sb.AppendLine($"\t\tvoid Handle{p.typeName}({p.typeName} message);");
		}
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic class McpeClientMessageDispatcher");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tprivate IMcpeClientMessageHandler _messageHandler = null;");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic McpeClientMessageDispatcher(IMcpeClientMessageHandler messageHandler)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_messageHandler = messageHandler;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic bool HandlePacket(Packet message)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tswitch (message)");
		sb.AppendLine("\t\t\t{");
		foreach (var p in handled.Where(p => p.server))
		{
			sb.AppendLine($"\t\t\t\tcase {p.typeName} msg:");
			sb.AppendLine($"\t\t\t\t\t_messageHandler.Handle{p.typeName}(msg);");
			sb.AppendLine("\t\t\t\t\tbreak;");
		}
		sb.AppendLine("\t\t\t\tdefault:");
		sb.AppendLine("\t\t\t\t\treturn false;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\treturn true;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic class PacketFactory");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tpublic static ICustomPacketFactory CustomPacketFactory { get; set; } = null;");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic static Packet Create(int messageId, ReadOnlyMemory<byte> buffer, string ns)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tPacket packet = CustomPacketFactory?.Create(messageId, buffer, ns);");
		sb.AppendLine("\t\t\tif (packet != null) return packet;");
		sb.AppendLine();
		sb.AppendLine("\t\t\tif(ns == \"raknet\") ");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace == "raknet"))
		{
			sb.AppendLine($"\t\t\t\t\tcase {pdu.Id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {CodeNames.CodeTypeName(pdu.Name)}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t} else if(ns == \"ftl\") ");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace == "ftl"))
		{
			sb.AppendLine($"\t\t\t\t\tcase {pdu.Id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {CodeNames.CodeTypeName(pdu.Name)}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t} else {");
		sb.AppendLine();
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (var p in mcpe)
		{
			sb.AppendLine($"\t\t\t\t\tcase {p.id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {p.typeName}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\treturn null;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		GeneratedFile.Write(path, sb);
	}
}

/// <summary>
///     Emits MCPE Protocol Cereal.cs: the packet classes generated from the Mojang schemas, in
///     exactly the shape the T4 template emits for XML packets.
/// </summary>
public static class CerealEmitter
{
	public static void Emit(string path, List<CerealPacket> packets, Dictionary<string, CerealStruct> structs)
	{
		var sb = new StringBuilder();
		sb.Append(GeneratedFile.LicenseHeader);
		sb.AppendLine();
		sb.AppendLine("//");
		sb.AppendLine("// WARNING: GENERATED CODE - DO NOT EDIT");
		sb.AppendLine("// Generated by MiNET.ProtocolGen from the JSON schemas of a BDS matching the targeted");
		sb.AppendLine("// protocol, plus roster.json and overrides.json.");
		sb.AppendLine("//");
		sb.AppendLine();
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine("using System.Numerics;");
		sb.AppendLine("using MiNET.Items;");
		sb.AppendLine("using MiNET.Utils;");
		sb.AppendLine("using MiNET.Utils.Metadata;");
		sb.AppendLine("using MiNET.Utils.Nbt;");
		sb.AppendLine("using MiNET.Utils.Skins;");
		sb.AppendLine("using MiNET.Utils.Vectors;");
		sb.AppendLine();
		sb.AppendLine("namespace MiNET.Net");
		sb.AppendLine("{");

		foreach (CerealPacket packet in packets.OrderBy(p => GeneratedFile.IdValue(p.Entry.Id)))
		{
			string typeName = packet.Entry.TypeName;
			string baseType = packet.Entry.Online ? "ConnectedPacket" : "Packet";

			sb.AppendLine($"\tpublic partial class {typeName} : {baseType}<{typeName}>");
			sb.AppendLine("\t{");
			foreach (CerealEnum e in packet.Enums)
			{
				sb.AppendLine($"\t\tpublic enum {e.Name}");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < e.Values.Count; i++)
				{
					sb.AppendLine($"\t\t\t{e.Values[i]} = {i},");
				}
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				sb.AppendLine($"\t\tpublic {field.CsType} {field.FieldName}; // = null;");
			}
			sb.AppendLine();
			sb.AppendLine($"\t\tpublic {typeName}()");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tId = {packet.Entry.Id};");
			sb.AppendLine("\t\t\tIsMcpe = true;");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void EncodePacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.EncodePacket();");
			sb.AppendLine();
			sb.AppendLine("\t\t\tBeforeEncode();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				foreach (string line in FieldWriteLines(field, "")) sb.AppendLine($"\t\t\t{line}");
			}
			sb.AppendLine();
			sb.AppendLine("\t\t\tAfterEncode();");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tpartial void BeforeEncode();");
			sb.AppendLine("\t\tpartial void AfterEncode();");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void DecodePacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.DecodePacket();");
			sb.AppendLine();
			sb.AppendLine("\t\t\tBeforeDecode();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				foreach (string line in FieldReadLines(field, "")) sb.AppendLine($"\t\t\t{line}");
			}
			sb.AppendLine();
			sb.AppendLine("\t\t\tAfterDecode();");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tpartial void BeforeDecode();");
			sb.AppendLine("\t\tpartial void AfterDecode();");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void ResetPacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.ResetPacket();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				sb.AppendLine($"\t\t\t{field.FieldName}=default({field.CsType});");
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		foreach (string baseName in structs.Values.Where(s => s.BaseName != null).Select(s => s.BaseName).Distinct().OrderBy(n => n))
		{
			sb.AppendLine($"\tpublic abstract class {baseName}");
			sb.AppendLine("\t{");
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		foreach (CerealStruct s in structs.Values.OrderBy(s => s.Name))
		{
			string inherit = s.BaseName != null ? $" : {s.BaseName}" : "";
			sb.AppendLine($"\tpublic class {s.Name}{inherit}");
			sb.AppendLine("\t{");
			foreach (CerealEnum e in s.Enums)
			{
				sb.AppendLine($"\t\tpublic enum {e.Name}");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < e.Values.Count; i++)
				{
					sb.AppendLine($"\t\t\t{e.Values[i]} = {i},");
				}
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}
			foreach (CerealField field in s.Fields.Where(f => f.ConstValue == null))
			{
				sb.AppendLine($"\t\tpublic {field.CsType} {field.FieldName};");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		if (structs.Count > 0)
		{
			sb.AppendLine("\tpublic abstract partial class Packet");
			sb.AppendLine("\t{");
			bool first = true;
			foreach (CerealStruct s in structs.Values.OrderBy(s => s.Name))
			{
				if (!first) sb.AppendLine();
				first = false;
				sb.AppendLine($"\t\tpublic void Write({s.Name} data)");
				sb.AppendLine("\t\t{");
				foreach (CerealField field in s.Fields)
				{
					foreach (string line in FieldWriteLines(field, "data.")) sb.AppendLine($"\t\t\t{line}");
				}
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine($"\t\tpublic {s.Name} Read{s.Name}()");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\tvar data = new {s.Name}();");
				foreach (CerealField field in s.Fields)
				{
					foreach (string line in FieldReadLines(field, "data.")) sb.AppendLine($"\t\t\t{line}");
				}
				sb.AppendLine("\t\t\treturn data;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		sb.AppendLine("}");

		GeneratedFile.Write(path, sb);
	}

	/// <summary>
	///     One field's encode, for a packet body (no prefix) or a struct codec ("data."). A
	///     discriminator const belongs to neither: it is a value the wire carries but the class does
	///     not hold, so it is written from the schema rather than from a member.
	/// </summary>
	private static IEnumerable<string> FieldWriteLines(CerealField field, string prefix)
	{
		if (field.ConstValue != null)
		{
			yield return string.Format(field.Type.Write, "");
			yield break;
		}
		foreach (string line in WriteLines(field, prefix)) yield return line;
	}

	private static IEnumerable<string> FieldReadLines(CerealField field, string prefix)
	{
		if (field.ConstValue != null)
		{
			yield return field.Type.Read;
			yield break;
		}
		foreach (string line in ReadLines(field, prefix)) yield return line;
	}

	private static IEnumerable<string> WriteLines(CerealField field, string prefix)
	{
		string name = prefix + field.FieldName;

		// A field that only travels for certain values of an earlier one. Not expressible in the
		// schema, and writing it unconditionally puts bytes on the wire the reader will not expect.
		if (field.PresentWhen != null)
		{
			foreach (string line in Conditional(field, prefix, WriteLinesInner(field, prefix))) yield return line;
			yield break;
		}

		foreach (string line in WriteLinesInner(field, prefix)) yield return line;
	}

	/// <summary>Wraps a field's lines in the "is it on the wire" test its condition describes.</summary>
	private static IEnumerable<string> Conditional(CerealField field, string prefix, IEnumerable<string> body)
	{
		string test = string.Join(" or ", field.PresentWhen.Values);
		string not = field.PresentWhen.Negated ? "not " : "";
		yield return $"if ((int) {prefix}{field.PresentWhen.Field} is {not}({test}))";
		yield return "{";
		foreach (string line in body) yield return "	" + line;
		yield return "}";
	}

	private static IEnumerable<string> WriteLinesInner(CerealField field, string prefix)
	{
		string name = prefix + field.FieldName;

		// An invariant-gated optional carries its gate byte first, always true when we are the one
		// deciding to send the field; the field's own presence byte follows in each branch below.
		if (field.Optional)
		{
			for (int gate = 1; gate < field.PresenceBytes; gate++) yield return "Write(true);";
		}

		if (field.Kind == FieldKind.Variant)
		{
			// Only the last slot survives the client's read, so the earlier ones are written absent.
			if (field.VariantSlots > 1)
			{
				yield return $"for (int slot = 0; slot < {field.VariantSlots - 1}; slot++) Write(false);";
			}

			string variantPad = field.Optional ? "\t" : "";
			if (field.Optional)
			{
				yield return $"Write({name} != null);";
				yield return $"if ({name} != null)";
				yield return "{";
			}

			// Discriminator and payload are two separate optionals in the engine, so each carries a
			// presence byte and the payload's sits between the tag and the data.
			if (field.VariantPayloadGate) yield return $"{variantPad}Write({name} != null);";

			yield return $"{variantPad}switch ({name})";
			yield return variantPad + "{";
			for (int i = 0; i < field.Variant.Options.Count; i++)
			{
				yield return $"{variantPad}\tcase {field.Variant.Options[i].Name} v{i}:";
				yield return $"{variantPad}\t\tWriteUnsignedVarInt({i});";
				if (field.VariantPayloadGate) yield return $"{variantPad}\t\tWrite(true);";
				yield return $"{variantPad}\t\tWrite(v{i});";
				yield return $"{variantPad}\t\tbreak;";
			}
			yield return $"{variantPad}\tdefault:";
			yield return $"{variantPad}\t\tthrow new Exception($\"{field.FieldName} variant not set or unknown: {{{name}}}\");";
			yield return variantPad + "}";

			if (field.Optional) yield return "}";
			yield break;
		}

		if (field.Kind == FieldKind.Struct)
		{
			if (field.Optional)
			{
				yield return $"Write({name} != null);";
				yield return $"if ({name} != null) Write({name});";
			}
			else
			{
				// Cereal has no null: a default-constructed value is what goes on the wire, so a
				// null reference writes as one (its vectors as zero counts, below).
				yield return $"Write({name} ?? new {field.Struct.Name}());";
			}
			yield break;
		}

		// A vector of tagged variants: each element carries its own discriminator, so the element
		// cannot be written by a single expression the way a struct or primitive can. PlayerList is
		// this shape since 2168, where add and remove entries are dispatched per entry.
		if (field.Kind == FieldKind.Array && field.Element.Kind == FieldKind.Variant)
		{
			if (field.Optional) yield return $"Write({name} != null);";
			yield return $"if ({name} != null)";
			yield return "{";
			yield return $"\tWriteUnsignedVarInt((uint) {name}.Count);";
			yield return $"\tforeach ({field.Element.CsType} item in {name})";
			yield return "\t{";
			yield return "\t\tswitch (item)";
			yield return "\t\t{";
			for (int i = 0; i < field.Element.Variant.Options.Count; i++)
			{
				yield return $"\t\t\tcase {field.Element.Variant.Options[i].Name} v{i}:";
				yield return $"\t\t\t\tWriteUnsignedVarInt({i});";
				yield return $"\t\t\t\tWrite(v{i});";
				yield return "\t\t\t\tbreak;";
			}
			yield return "\t\t\tdefault:";
			yield return $"\t\t\t\tthrow new Exception($\"{field.FieldName} element variant not set or unknown: {{item}}\");";
			yield return "\t\t}";
			yield return "\t}";
			yield return "}";
			// Cereal has no null: a required vector that was never set is an empty vector, count 0.
			if (!field.Optional) yield return $"else WriteUnsignedVarInt(0);";
			yield break;
		}

		if (field.Kind == FieldKind.Map)
		{
			string entryValue = field.Element.Enum != null ? $"({field.Element.Type.CsType}) entry.Value" : "entry.Value";
			string writeValue = field.Element.Kind == FieldKind.Struct ? "Write(entry.Value);" : string.Format(field.Element.Type.Write, entryValue);
			if (field.Optional)
			{
				yield return $"Write({name} != null);";
				yield return $"if ({name} != null)";
				yield return "{";
				yield return $"\tWriteUnsignedVarInt((uint) {name}.Count);";
				yield return $"\tforeach (KeyValuePair<string, {field.Element.CsType}> entry in {name}) {{ Write(entry.Key); {writeValue} }}";
				yield return "}";
			}
			else
			{
				// Cereal has no null: an unset map is an empty map, count 0.
				yield return $"WriteUnsignedVarInt((uint) ({name}?.Count ?? 0));";
				yield return $"if ({name} != null) foreach (KeyValuePair<string, {field.Element.CsType}> entry in {name}) {{ Write(entry.Key); {writeValue} }}";
			}
			yield break;
		}

		if (field.Kind == FieldKind.Array)
		{
			string itemValue = field.Element.Enum != null ? $"({field.Element.Type.CsType}) item" : "item";
			string writeItem = field.Element.Kind == FieldKind.Struct ? "Write(item);" : string.Format(field.Element.Type.Write, itemValue);
			if (field.Optional)
			{
				yield return $"Write({name} != null);";
				yield return $"if ({name} != null)";
				yield return "{";
				yield return $"\tWriteUnsignedVarInt((uint) {name}.Count);";
				yield return $"\tforeach ({field.Element.CsType} item in {name}) {writeItem}";
				yield return "}";
			}
			else
			{
				// Cereal has no null: an unset vector is an empty vector, count 0.
				yield return $"WriteUnsignedVarInt((uint) ({name}?.Count ?? 0));";
				yield return $"if ({name} != null) foreach ({field.Element.CsType} item in {name}) {writeItem}";
			}
			yield break;
		}

		if (field.Optional)
		{
			string value = field.IsValueType ? name + ".Value" : name;
			// Enum-typed fields go on the wire as their underlying primitive.
			if (field.Enum != null) value = $"({field.Type.CsType}) {value}";
			yield return $"Write({name} != null);";
			yield return $"if ({name} != null) {string.Format(field.Type.Write, value)}";
			yield break;
		}

		yield return string.Format(field.Type.Write, field.Enum != null ? $"({field.Type.CsType}) {name}" : name);
	}

	private static IEnumerable<string> ReadLines(CerealField field, string prefix)
	{
		if (field.PresentWhen != null)
		{
			foreach (string line in Conditional(field, prefix, ReadLinesInner(field, prefix))) yield return line;
			yield break;
		}

		foreach (string line in ReadLinesInner(field, prefix)) yield return line;
	}

	private static IEnumerable<string> ReadLinesInner(CerealField field, string prefix)
	{
		string name = prefix + field.FieldName;
		// Absent when ANY gate byte is false, and the later ones are then not on the wire at all,
		// so this has to short-circuit rather than read a fixed number of bytes.
		string present = string.Join(" && ", Enumerable.Repeat("ReadBool()", field.PresenceBytes));

		if (field.Kind == FieldKind.Variant)
		{
			string variantPad = "";
			if (field.Optional)
			{
				// Every slot carries the same field, so the last one present is the value.
				if (field.VariantSlots > 1)
				{
					yield return $"{name} = null;";
					yield return $"for (int slot = 0; slot < {field.VariantSlots}; slot++)";
					yield return "{";
					yield return "\tif (!ReadBool()) continue;";
				}
				else
				{
					yield return $"if (!({present})) {name} = null;";
					yield return "else";
					yield return "{";
				}

				variantPad = "\t";
			}

			// The engine keeps the discriminator and the payload as two separate optionals, so each
			// carries its own presence byte and the second one sits between the tag and the data.
			if (field.VariantPayloadGate) yield return $"{variantPad}ReadBool(); // discriminator presence";
			yield return $"{variantPad}uint {field.FieldName}Tag = ReadUnsignedVarInt();";
			if (field.VariantPayloadGate) yield return $"{variantPad}ReadBool(); // payload presence";
			yield return $"{variantPad}{name} = {field.FieldName}Tag switch";
			yield return variantPad + "{";
			for (int i = 0; i < field.Variant.Options.Count; i++)
			{
				yield return $"{variantPad}\t{i} => Read{field.Variant.Options[i].Name}(),";
			}
			yield return $"{variantPad}\tuint other => throw new Exception($\"Unknown {field.FieldName} variant tag {{other}}\"),";
			yield return variantPad + "};";

			if (field.Optional) yield return "}";
			yield break;
		}

		if (field.Kind == FieldKind.Struct)
		{
			if (field.Optional)
			{
				yield return $"if ({present}) {name} = Read{field.Struct.Name}();";
			}
			else
			{
				yield return $"{name} = Read{field.Struct.Name}();";
			}
			yield break;
		}

		if (field.Kind == FieldKind.Map)
		{
			if (field.Optional)
			{
				yield return $"if ({present})";
				yield return "{";
				yield return $"\tuint {field.FieldName}Count = ReadUnsignedVarInt();";
				yield return $"\t{name} = new Dictionary<string, {field.Element.CsType}>((int) {field.FieldName}Count);";
				yield return $"\tfor (int i = 0; i < {field.FieldName}Count; i++) {name}.TryAdd(ReadString(), {ReadExpression(field.Element)});";
				yield return "}";
			}
			else
			{
				yield return $"uint {field.FieldName}Count = ReadUnsignedVarInt();";
				yield return $"{name} = new Dictionary<string, {field.Element.CsType}>((int) {field.FieldName}Count);";
				yield return $"for (int i = 0; i < {field.FieldName}Count; i++) {name}.TryAdd(ReadString(), {ReadExpression(field.Element)});";
			}
			yield break;
		}

		if (field.Kind == FieldKind.Array)
		{
			if (field.Optional)
			{
				yield return $"if ({present})";
				yield return "{";
				yield return $"\tuint {field.FieldName}Count = ReadUnsignedVarInt();";
				yield return $"\t{name} = new List<{field.Element.CsType}>((int) {field.FieldName}Count);";
				yield return $"\tfor (int i = 0; i < {field.FieldName}Count; i++) {name}.Add({ReadExpression(field.Element)});";
				yield return "}";
			}
			else
			{
				yield return $"uint {field.FieldName}Count = ReadUnsignedVarInt();";
				yield return $"{name} = new List<{field.Element.CsType}>((int) {field.FieldName}Count);";
				yield return $"for (int i = 0; i < {field.FieldName}Count; i++) {name}.Add({ReadExpression(field.Element)});";
			}
			yield break;
		}

		if (field.Optional)
		{
			yield return $"if ({present}) {name} = {ReadExpression(field)};";
			yield break;
		}

		if (field.Enum != null)
		{
			yield return $"{name} = {ReadExpression(field)};";
			yield break;
		}

		yield return string.Format(field.Type.Read, name);
	}

	/// <summary>The read call as an expression, for array elements: "ReadString()" from "{0} = ReadString();".</summary>
	private static string ReadExpression(CerealField element)
	{
		if (element.Kind == FieldKind.Struct) return $"Read{element.Struct.Name}()";

		// Each element of a variant vector reads its own discriminator first.
		if (element.Kind == FieldKind.Variant)
		{
			string arms = string.Join(" ", element.Variant.Options.Select((o, i) => $"{i} => Read{o.Name}(),"));
			return $"ReadUnsignedVarInt() switch {{ {arms} uint other => throw new Exception($\"Unknown {element.FieldName} variant tag {{other}}\") }}";
		}

		string read = string.Format(element.Type.Read, "");
		if (!read.StartsWith(" = ") || !read.EndsWith(";"))
			throw new NotImplementedException($"array element read is not expression-shaped: {element.Type.Read}");
		string expression = read.Substring(3, read.Length - 4);
		// Enum-typed fields come off the wire as their underlying primitive.
		return element.Enum != null ? $"({element.EnumRef ?? element.Enum.Name}) {expression}" : expression;
	}
}
