#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
//
// The Original Code is MiNET.
//
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
//
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson.
// All Rights Reserved.

#endregion

//
// WARNING: GENERATED CODE - DO NOT EDIT
// Generated by MiNET.ProtocolGen from MCPE Protocol.xml and roster.json.
//

using System;

namespace MiNET.Net
{
	public interface IMcpeMessageHandler
	{
		void Disconnect(string reason, bool sendDisconnect = true);

		void HandleMcpeLogin(McpeLogin message);
		void HandleMcpeClientToServerHandshake(McpeClientToServerHandshake message);
		void HandleMcpeResourcePackClientResponse(McpeResourcePackClientResponse message);
		void HandleMcpeText(McpeText message);
		void HandleMcpeMoveEntity(McpeMoveEntity message);
		void HandleMcpeMovePlayer(McpeMovePlayer message);
		void HandleMcpeEntityEvent(McpeEntityEvent message);
		void HandleMcpeInventoryTransaction(McpeInventoryTransaction message);
		void HandleMcpeMobEquipment(McpeMobEquipment message);
		void HandleMcpeMobArmorEquipment(McpeMobArmorEquipment message);
		void HandleMcpeInteract(McpeInteract message);
		void HandleMcpeBlockPickRequest(McpeBlockPickRequest message);
		void HandleMcpeEntityPickRequest(McpeEntityPickRequest message);
		void HandleMcpePlayerAction(McpePlayerAction message);
		void HandleMcpeSetEntityData(McpeSetEntityData message);
		void HandleMcpeSetEntityMotion(McpeSetEntityMotion message);
		void HandleMcpeAnimate(McpeAnimate message);
		void HandleMcpeRespawn(McpeRespawn message);
		void HandleMcpeContainerClose(McpeContainerClose message);
		void HandleMcpePlayerHotbar(McpePlayerHotbar message);
		void HandleMcpeInventoryContent(McpeInventoryContent message);
		void HandleMcpeInventorySlot(McpeInventorySlot message);
		void HandleMcpeBlockEntityData(McpeBlockEntityData message);
		void HandleMcpeSetPlayerGameType(McpeSetPlayerGameType message);
		void HandleMcpeMapInfoRequest(McpeMapInfoRequest message);
		void HandleMcpeRequestChunkRadius(McpeRequestChunkRadius message);
		void HandleMcpeCommandRequest(McpeCommandRequest message);
		void HandleMcpeCommandBlockUpdate(McpeCommandBlockUpdate message);
		void HandleMcpeResourcePackChunkRequest(McpeResourcePackChunkRequest message);
		void HandleMcpePurchaseReceipt(McpePurchaseReceipt message);
		void HandleMcpePlayerSkin(McpePlayerSkin message);
		void HandleMcpeNpcRequest(McpeNpcRequest message);
		void HandleMcpePhotoTransfer(McpePhotoTransfer message);
		void HandleMcpeModalFormResponse(McpeModalFormResponse message);
		void HandleMcpeServerSettingsRequest(McpeServerSettingsRequest message);
		void HandleMcpeLabTable(McpeLabTable message);
		void HandleMcpeSetLocalPlayerAsInitialized(McpeSetLocalPlayerAsInitialized message);
		void HandleMcpeNetworkStackLatency(McpeNetworkStackLatency message);
		void HandleMcpeLevelSoundEvent(McpeLevelSoundEvent message);
		void HandleMcpeClientCacheStatus(McpeClientCacheStatus message);
		void HandleMcpeClientCacheBlobStatus(McpeClientCacheBlobStatus message);
		void HandleMcpeEmote(McpeEmote message);
		void HandleMcpeMultiplayerSettings(McpeMultiplayerSettings message);
		void HandleMcpeSettingsCommand(McpeSettingsCommand message);
		void HandleMcpeAnvilDamage(McpeAnvilDamage message);
		void HandleMcpePlayerAuthInput(McpePlayerAuthInput message);
		void HandleMcpeItemStackRequest(McpeItemStackRequest message);
		void HandleMcpeUpdatePlayerGameType(McpeUpdatePlayerGameType message);
		void HandleMcpeEmoteList(McpeEmoteList message);
		void HandleMcpePositionTrackingDbClientRequest(McpePositionTrackingDbClientRequest message);
		void HandleMcpeDebugInfo(McpeDebugInfo message);
		void HandleMcpePacketViolationWarning(McpePacketViolationWarning message);
		void HandleMcpeCreatePhoto(McpeCreatePhoto message);
		void HandleMcpeUpdateSubChunkBlocksPacket(McpeUpdateSubChunkBlocksPacket message);
		void HandleMcpeSubChunkRequestPacket(McpeSubChunkRequestPacket message);
		void HandleMcpeScriptMessage(McpeScriptMessage message);
		void HandleMcpeCodeBuilderSource(McpeCodeBuilderSource message);
		void HandleMcpeChangeMobProperty(McpeChangeMobProperty message);
		void HandleMcpeRequestAbility(McpeRequestAbility message);
		void HandleMcpeRequestPermissions(McpeRequestPermissions message);
		void HandleMcpeEditorNetwork(McpeEditorNetwork message);
		void HandleMcpeRequestNetworkSettings(McpeRequestNetworkSettings message);
		void HandleMcpeGameTestRequest(McpeGameTestRequest message);
		void HandleMcpePlayerToggleCrafterSlotRequest(McpePlayerToggleCrafterSlotRequest message);
		void HandleMcpeSetPlayerInventoryOptions(McpeSetPlayerInventoryOptions message);
		void HandleMcpeServerBoundLoadingScreen(McpeServerBoundLoadingScreen message);
		void HandleMcpeServerBoundDiagnostics(McpeServerBoundDiagnostics message);
		void HandleMcpeClientCameraAimAssist(McpeClientCameraAimAssist message);
		void HandleMcpeClientMovementPredictionSync(McpeClientMovementPredictionSync message);
		void HandleMcpeUpdateClientOptions(McpeUpdateClientOptions message);
		void HandleMcpeServerboundPackSettingChange(McpeServerboundPackSettingChange message);
		void HandleMcpeServerboundDataStore(McpeServerboundDataStore message);
		void HandleMcpeResourcePacksReadyForValidation(McpeResourcePacksReadyForValidation message);
		void HandleMcpePartyChanged(McpePartyChanged message);
		void HandleMcpeServerboundDataDrivenScreenClosed(McpeServerboundDataDrivenScreenClosed message);
		void HandleMcpePartyDestinationCookieResponse(McpePartyDestinationCookieResponse message);
		void HandleMcpeSetPlayerFurnaceOptions(McpeSetPlayerFurnaceOptions message);
	}

	public interface IMcpeClientMessageHandler
	{
		void HandleFtlCreatePlayer(FtlCreatePlayer message);
		void HandleMcpePlayStatus(McpePlayStatus message);
		void HandleMcpeServerToClientHandshake(McpeServerToClientHandshake message);
		void HandleMcpeDisconnect(McpeDisconnect message);
		void HandleMcpeResourcePacksInfo(McpeResourcePacksInfo message);
		void HandleMcpeResourcePackStack(McpeResourcePackStack message);
		void HandleMcpeText(McpeText message);
		void HandleMcpeSetTime(McpeSetTime message);
		void HandleMcpeStartGame(McpeStartGame message);
		void HandleMcpeAddPlayer(McpeAddPlayer message);
		void HandleMcpeAddEntity(McpeAddEntity message);
		void HandleMcpeRemoveEntity(McpeRemoveEntity message);
		void HandleMcpeAddItemEntity(McpeAddItemEntity message);
		void HandleMcpeServerPlayerPostMovePosition(McpeServerPlayerPostMovePosition message);
		void HandleMcpeTakeItemEntity(McpeTakeItemEntity message);
		void HandleMcpeMoveEntity(McpeMoveEntity message);
		void HandleMcpeMovePlayer(McpeMovePlayer message);
		void HandleMcpeUpdateBlock(McpeUpdateBlock message);
		void HandleMcpeAddPainting(McpeAddPainting message);
		void HandleMcpeLevelEvent(McpeLevelEvent message);
		void HandleMcpeBlockEvent(McpeBlockEvent message);
		void HandleMcpeEntityEvent(McpeEntityEvent message);
		void HandleMcpeMobEffect(McpeMobEffect message);
		void HandleMcpeUpdateAttributes(McpeUpdateAttributes message);
		void HandleMcpeInventoryTransaction(McpeInventoryTransaction message);
		void HandleMcpeMobEquipment(McpeMobEquipment message);
		void HandleMcpeMobArmorEquipment(McpeMobArmorEquipment message);
		void HandleMcpeInteract(McpeInteract message);
		void HandleMcpeHurtArmor(McpeHurtArmor message);
		void HandleMcpeSetEntityData(McpeSetEntityData message);
		void HandleMcpeSetEntityMotion(McpeSetEntityMotion message);
		void HandleMcpeSetEntityLink(McpeSetEntityLink message);
		void HandleMcpeSetHealth(McpeSetHealth message);
		void HandleMcpeSetSpawnPosition(McpeSetSpawnPosition message);
		void HandleMcpeAnimate(McpeAnimate message);
		void HandleMcpeRespawn(McpeRespawn message);
		void HandleMcpeContainerOpen(McpeContainerOpen message);
		void HandleMcpeContainerClose(McpeContainerClose message);
		void HandleMcpePlayerHotbar(McpePlayerHotbar message);
		void HandleMcpeInventoryContent(McpeInventoryContent message);
		void HandleMcpeInventorySlot(McpeInventorySlot message);
		void HandleMcpeContainerSetData(McpeContainerSetData message);
		void HandleMcpeCraftingData(McpeCraftingData message);
		void HandleMcpeGuiDataPickItem(McpeGuiDataPickItem message);
		void HandleMcpeBlockEntityData(McpeBlockEntityData message);
		void HandleMcpeLevelChunk(McpeLevelChunk message);
		void HandleMcpeSetCommandsEnabled(McpeSetCommandsEnabled message);
		void HandleMcpeSetDifficulty(McpeSetDifficulty message);
		void HandleMcpeChangeDimension(McpeChangeDimension message);
		void HandleMcpeSetPlayerGameType(McpeSetPlayerGameType message);
		void HandleMcpePlayerList(McpePlayerList message);
		void HandleMcpeSimpleEvent(McpeSimpleEvent message);
		void HandleMcpeTelemetryEvent(McpeTelemetryEvent message);
		void HandleMcpeSpawnExperienceOrb(McpeSpawnExperienceOrb message);
		void HandleMcpeClientboundMapItemData(McpeClientboundMapItemData message);
		void HandleMcpeMapInfoRequest(McpeMapInfoRequest message);
		void HandleMcpeRequestChunkRadius(McpeRequestChunkRadius message);
		void HandleMcpeChunkRadiusUpdate(McpeChunkRadiusUpdate message);
		void HandleMcpeGameRulesChanged(McpeGameRulesChanged message);
		void HandleMcpeCamera(McpeCamera message);
		void HandleMcpeBossEvent(McpeBossEvent message);
		void HandleMcpeShowCredits(McpeShowCredits message);
		void HandleMcpeAvailableCommands(McpeAvailableCommands message);
		void HandleMcpeCommandOutput(McpeCommandOutput message);
		void HandleMcpeUpdateTrade(McpeUpdateTrade message);
		void HandleMcpeUpdateEquipment(McpeUpdateEquipment message);
		void HandleMcpeResourcePackDataInfo(McpeResourcePackDataInfo message);
		void HandleMcpeResourcePackChunkData(McpeResourcePackChunkData message);
		void HandleMcpeTransfer(McpeTransfer message);
		void HandleMcpePlaySound(McpePlaySound message);
		void HandleMcpeStopSound(McpeStopSound message);
		void HandleMcpeSetTitle(McpeSetTitle message);
		void HandleMcpeAddBehaviorTree(McpeAddBehaviorTree message);
		void HandleMcpeStructureBlockUpdate(McpeStructureBlockUpdate message);
		void HandleMcpeShowStoreOffer(McpeShowStoreOffer message);
		void HandleMcpePlayerSkin(McpePlayerSkin message);
		void HandleMcpeSubClientLogin(McpeSubClientLogin message);
		void HandleMcpeInitiateWebSocketConnection(McpeInitiateWebSocketConnection message);
		void HandleMcpeSetLastHurtBy(McpeSetLastHurtBy message);
		void HandleMcpeBookEdit(McpeBookEdit message);
		void HandleMcpeNpcRequest(McpeNpcRequest message);
		void HandleMcpeModalFormRequest(McpeModalFormRequest message);
		void HandleMcpeServerSettingsResponse(McpeServerSettingsResponse message);
		void HandleMcpeShowProfile(McpeShowProfile message);
		void HandleMcpeSetDefaultGameType(McpeSetDefaultGameType message);
		void HandleMcpeRemoveObjective(McpeRemoveObjective message);
		void HandleMcpeSetDisplayObjective(McpeSetDisplayObjective message);
		void HandleMcpeSetScore(McpeSetScore message);
		void HandleMcpeLabTable(McpeLabTable message);
		void HandleMcpeUpdateBlockSynced(McpeUpdateBlockSynced message);
		void HandleMcpeMoveEntityDelta(McpeMoveEntityDelta message);
		void HandleMcpeSetScoreboardIdentity(McpeSetScoreboardIdentity message);
		void HandleMcpeUpdateSoftEnum(McpeUpdateSoftEnum message);
		void HandleMcpeNetworkStackLatency(McpeNetworkStackLatency message);
		void HandleMcpeSpawnParticleEffect(McpeSpawnParticleEffect message);
		void HandleMcpeAvailableEntityIdentifiers(McpeAvailableEntityIdentifiers message);
		void HandleMcpeNetworkChunkPublisherUpdate(McpeNetworkChunkPublisherUpdate message);
		void HandleMcpeBiomeDefinitionList(McpeBiomeDefinitionList message);
		void HandleMcpeLevelSoundEvent(McpeLevelSoundEvent message);
		void HandleMcpeLevelEventGeneric(McpeLevelEventGeneric message);
		void HandleMcpeLecternUpdate(McpeLecternUpdate message);
		void HandleMcpeClientCacheStatus(McpeClientCacheStatus message);
		void HandleMcpeOnScreenTextureAnimation(McpeOnScreenTextureAnimation message);
		void HandleMcpeMapCreateLockedCopy(McpeMapCreateLockedCopy message);
		void HandleMcpeStructureTemplateDataExportRequest(McpeStructureTemplateDataExportRequest message);
		void HandleMcpeStructureTemplateDataExportResponse(McpeStructureTemplateDataExportResponse message);
		void HandleMcpeClientCacheMissResponse(McpeClientCacheMissResponse message);
		void HandleMcpeEducationSettings(McpeEducationSettings message);
		void HandleMcpeEmote(McpeEmote message);
		void HandleMcpeMultiplayerSettings(McpeMultiplayerSettings message);
		void HandleMcpeCompletedUsingItem(McpeCompletedUsingItem message);
		void HandleMcpeNetworkSettings(McpeNetworkSettings message);
		void HandleMcpeCreativeContent(McpeCreativeContent message);
		void HandleMcpePlayerEnchantOptions(McpePlayerEnchantOptions message);
		void HandleMcpeItemStackResponse(McpeItemStackResponse message);
		void HandleMcpePlayerArmorDamage(McpePlayerArmorDamage message);
		void HandleMcpeCodeBuilder(McpeCodeBuilder message);
		void HandleMcpePositionTrackingDbServerBroadcast(McpePositionTrackingDbServerBroadcast message);
		void HandleMcpeDebugInfo(McpeDebugInfo message);
		void HandleMcpeMotionPredictionHints(McpeMotionPredictionHints message);
		void HandleMcpeAnimateEntity(McpeAnimateEntity message);
		void HandleMcpeCameraShake(McpeCameraShake message);
		void HandleMcpePlayerFog(McpePlayerFog message);
		void HandleMcpeCorrectPlayerMovePrediction(McpeCorrectPlayerMovePrediction message);
		void HandleMcpeItemComponent(McpeItemComponent message);
		void HandleMcpeClientboundDebugRenderer(McpeClientboundDebugRenderer message);
		void HandleMcpeSyncEntityProperty(McpeSyncEntityProperty message);
		void HandleMcpeAddVolumeEntity(McpeAddVolumeEntity message);
		void HandleMcpeRemoveVolumeEntity(McpeRemoveVolumeEntity message);
		void HandleMcpeSimulationType(McpeSimulationType message);
		void HandleMcpeNpcDialogue(McpeNpcDialogue message);
		void HandleMcpeEduUriResource(McpeEduUriResource message);
		void HandleMcpeUpdateSubChunkBlocksPacket(McpeUpdateSubChunkBlocksPacket message);
		void HandleMcpeSubChunkPacket(McpeSubChunkPacket message);
		void HandleMcpePlayerStartItemCooldown(McpePlayerStartItemCooldown message);
		void HandleMcpeScriptMessage(McpeScriptMessage message);
		void HandleMcpeTickingAreasLoadStatus(McpeTickingAreasLoadStatus message);
		void HandleMcpeDimensionData(McpeDimensionData message);
		void HandleMcpeAgentActionEvent(McpeAgentActionEvent message);
		void HandleMcpeLessonProgress(McpeLessonProgress message);
		void HandleMcpeToastRequest(McpeToastRequest message);
		void HandleMcpeUpdateAbilities(McpeUpdateAbilities message);
		void HandleMcpeUpdateAdventureSettings(McpeUpdateAdventureSettings message);
		void HandleMcpeDeathInfo(McpeDeathInfo message);
		void HandleMcpeEditorNetwork(McpeEditorNetwork message);
		void HandleMcpeFeatureRegistry(McpeFeatureRegistry message);
		void HandleMcpeServerStats(McpeServerStats message);
		void HandleMcpeGameTestResults(McpeGameTestResults message);
		void HandleMcpeUpdateClientInputLocks(McpeUpdateClientInputLocks message);
		void HandleMcpeCameraPresets(McpeCameraPresets message);
		void HandleMcpeUnlockedRecipes(McpeUnlockedRecipes message);
		void HandleMcpeCameraInstruction(McpeCameraInstruction message);
		void HandleMcpeTrimData(McpeTrimData message);
		void HandleMcpeOpenSign(McpeOpenSign message);
		void HandleMcpeAgentAnimation(McpeAgentAnimation message);
		void HandleMcpeRefreshEntitlements(McpeRefreshEntitlements message);
		void HandleMcpeSetHud(McpeSetHud message);
		void HandleMcpeAwardAchievement(McpeAwardAchievement message);
		void HandleMcpeClientboundCloseForm(McpeClientboundCloseForm message);
		void HandleMcpeJigsawStructureData(McpeJigsawStructureData message);
		void HandleMcpeCurrentStructureFeature(McpeCurrentStructureFeature message);
		void HandleMcpeCameraAimAssist(McpeCameraAimAssist message);
		void HandleMcpeContainerRegistryCleanup(McpeContainerRegistryCleanup message);
		void HandleMcpeMovementEffect(McpeMovementEffect message);
		void HandleMcpeCameraAimAssistPresets(McpeCameraAimAssistPresets message);
		void HandleMcpePlayerVideoCapture(McpePlayerVideoCapture message);
		void HandleMcpePlayerUpdateEntityOverrides(McpePlayerUpdateEntityOverrides message);
		void HandleMcpePlayerLocation(McpePlayerLocation message);
		void HandleMcpeClientboundControlSchemeSet(McpeClientboundControlSchemeSet message);
		void HandleMcpePrimitiveShapes(McpePrimitiveShapes message);
		void HandleMcpeClientboundDataStore(McpeClientboundDataStore message);
		void HandleMcpeGraphicsOverrideParameter(McpeGraphicsOverrideParameter message);
		void HandleMcpeClientboundDataDrivenUiShowScreen(McpeClientboundDataDrivenUiShowScreen message);
		void HandleMcpeClientboundDataDrivenUiCloseScreen(McpeClientboundDataDrivenUiCloseScreen message);
		void HandleMcpeClientboundDataDrivenUiReload(McpeClientboundDataDrivenUiReload message);
		void HandleMcpeClientboundTextureShift(McpeClientboundTextureShift message);
		void HandleMcpeVoxelShapes(McpeVoxelShapes message);
		void HandleMcpeCameraSpline(McpeCameraSpline message);
		void HandleMcpeCameraAimAssistActorPriority(McpeCameraAimAssistActorPriority message);
		void HandleMcpeLocatorBar(McpeLocatorBar message);
		void HandleMcpeSyncWorldClocks(McpeSyncWorldClocks message);
		void HandleMcpeClientboundAttributeLayerSync(McpeClientboundAttributeLayerSync message);
		void HandleMcpeServerStoreInfo(McpeServerStoreInfo message);
		void HandleMcpeServerPresenceInfo(McpeServerPresenceInfo message);
		void HandleMcpeClientboundUpdateSoundData(McpeClientboundUpdateSoundData message);
		void HandleMcpeSendPartyDestinationCookie(McpeSendPartyDestinationCookie message);
		void HandleMcpeSetPlayerFurnaceOptions(McpeSetPlayerFurnaceOptions message);
		void HandleMcpeRecordStarted(McpeRecordStarted message);
	}

	public class McpeClientMessageDispatcher
	{
		private IMcpeClientMessageHandler _messageHandler = null;

		public McpeClientMessageDispatcher(IMcpeClientMessageHandler messageHandler)
		{
			_messageHandler = messageHandler;
		}

		public bool HandlePacket(Packet message)
		{
			switch (message)
			{
				case FtlCreatePlayer msg:
					_messageHandler.HandleFtlCreatePlayer(msg);
					break;
				case McpePlayStatus msg:
					_messageHandler.HandleMcpePlayStatus(msg);
					break;
				case McpeServerToClientHandshake msg:
					_messageHandler.HandleMcpeServerToClientHandshake(msg);
					break;
				case McpeDisconnect msg:
					_messageHandler.HandleMcpeDisconnect(msg);
					break;
				case McpeResourcePacksInfo msg:
					_messageHandler.HandleMcpeResourcePacksInfo(msg);
					break;
				case McpeResourcePackStack msg:
					_messageHandler.HandleMcpeResourcePackStack(msg);
					break;
				case McpeText msg:
					_messageHandler.HandleMcpeText(msg);
					break;
				case McpeSetTime msg:
					_messageHandler.HandleMcpeSetTime(msg);
					break;
				case McpeStartGame msg:
					_messageHandler.HandleMcpeStartGame(msg);
					break;
				case McpeAddPlayer msg:
					_messageHandler.HandleMcpeAddPlayer(msg);
					break;
				case McpeAddEntity msg:
					_messageHandler.HandleMcpeAddEntity(msg);
					break;
				case McpeRemoveEntity msg:
					_messageHandler.HandleMcpeRemoveEntity(msg);
					break;
				case McpeAddItemEntity msg:
					_messageHandler.HandleMcpeAddItemEntity(msg);
					break;
				case McpeServerPlayerPostMovePosition msg:
					_messageHandler.HandleMcpeServerPlayerPostMovePosition(msg);
					break;
				case McpeTakeItemEntity msg:
					_messageHandler.HandleMcpeTakeItemEntity(msg);
					break;
				case McpeMoveEntity msg:
					_messageHandler.HandleMcpeMoveEntity(msg);
					break;
				case McpeMovePlayer msg:
					_messageHandler.HandleMcpeMovePlayer(msg);
					break;
				case McpeUpdateBlock msg:
					_messageHandler.HandleMcpeUpdateBlock(msg);
					break;
				case McpeAddPainting msg:
					_messageHandler.HandleMcpeAddPainting(msg);
					break;
				case McpeLevelEvent msg:
					_messageHandler.HandleMcpeLevelEvent(msg);
					break;
				case McpeBlockEvent msg:
					_messageHandler.HandleMcpeBlockEvent(msg);
					break;
				case McpeEntityEvent msg:
					_messageHandler.HandleMcpeEntityEvent(msg);
					break;
				case McpeMobEffect msg:
					_messageHandler.HandleMcpeMobEffect(msg);
					break;
				case McpeUpdateAttributes msg:
					_messageHandler.HandleMcpeUpdateAttributes(msg);
					break;
				case McpeInventoryTransaction msg:
					_messageHandler.HandleMcpeInventoryTransaction(msg);
					break;
				case McpeMobEquipment msg:
					_messageHandler.HandleMcpeMobEquipment(msg);
					break;
				case McpeMobArmorEquipment msg:
					_messageHandler.HandleMcpeMobArmorEquipment(msg);
					break;
				case McpeInteract msg:
					_messageHandler.HandleMcpeInteract(msg);
					break;
				case McpeHurtArmor msg:
					_messageHandler.HandleMcpeHurtArmor(msg);
					break;
				case McpeSetEntityData msg:
					_messageHandler.HandleMcpeSetEntityData(msg);
					break;
				case McpeSetEntityMotion msg:
					_messageHandler.HandleMcpeSetEntityMotion(msg);
					break;
				case McpeSetEntityLink msg:
					_messageHandler.HandleMcpeSetEntityLink(msg);
					break;
				case McpeSetHealth msg:
					_messageHandler.HandleMcpeSetHealth(msg);
					break;
				case McpeSetSpawnPosition msg:
					_messageHandler.HandleMcpeSetSpawnPosition(msg);
					break;
				case McpeAnimate msg:
					_messageHandler.HandleMcpeAnimate(msg);
					break;
				case McpeRespawn msg:
					_messageHandler.HandleMcpeRespawn(msg);
					break;
				case McpeContainerOpen msg:
					_messageHandler.HandleMcpeContainerOpen(msg);
					break;
				case McpeContainerClose msg:
					_messageHandler.HandleMcpeContainerClose(msg);
					break;
				case McpePlayerHotbar msg:
					_messageHandler.HandleMcpePlayerHotbar(msg);
					break;
				case McpeInventoryContent msg:
					_messageHandler.HandleMcpeInventoryContent(msg);
					break;
				case McpeInventorySlot msg:
					_messageHandler.HandleMcpeInventorySlot(msg);
					break;
				case McpeContainerSetData msg:
					_messageHandler.HandleMcpeContainerSetData(msg);
					break;
				case McpeCraftingData msg:
					_messageHandler.HandleMcpeCraftingData(msg);
					break;
				case McpeGuiDataPickItem msg:
					_messageHandler.HandleMcpeGuiDataPickItem(msg);
					break;
				case McpeBlockEntityData msg:
					_messageHandler.HandleMcpeBlockEntityData(msg);
					break;
				case McpeLevelChunk msg:
					_messageHandler.HandleMcpeLevelChunk(msg);
					break;
				case McpeSetCommandsEnabled msg:
					_messageHandler.HandleMcpeSetCommandsEnabled(msg);
					break;
				case McpeSetDifficulty msg:
					_messageHandler.HandleMcpeSetDifficulty(msg);
					break;
				case McpeChangeDimension msg:
					_messageHandler.HandleMcpeChangeDimension(msg);
					break;
				case McpeSetPlayerGameType msg:
					_messageHandler.HandleMcpeSetPlayerGameType(msg);
					break;
				case McpePlayerList msg:
					_messageHandler.HandleMcpePlayerList(msg);
					break;
				case McpeSimpleEvent msg:
					_messageHandler.HandleMcpeSimpleEvent(msg);
					break;
				case McpeTelemetryEvent msg:
					_messageHandler.HandleMcpeTelemetryEvent(msg);
					break;
				case McpeSpawnExperienceOrb msg:
					_messageHandler.HandleMcpeSpawnExperienceOrb(msg);
					break;
				case McpeClientboundMapItemData msg:
					_messageHandler.HandleMcpeClientboundMapItemData(msg);
					break;
				case McpeMapInfoRequest msg:
					_messageHandler.HandleMcpeMapInfoRequest(msg);
					break;
				case McpeRequestChunkRadius msg:
					_messageHandler.HandleMcpeRequestChunkRadius(msg);
					break;
				case McpeChunkRadiusUpdate msg:
					_messageHandler.HandleMcpeChunkRadiusUpdate(msg);
					break;
				case McpeGameRulesChanged msg:
					_messageHandler.HandleMcpeGameRulesChanged(msg);
					break;
				case McpeCamera msg:
					_messageHandler.HandleMcpeCamera(msg);
					break;
				case McpeBossEvent msg:
					_messageHandler.HandleMcpeBossEvent(msg);
					break;
				case McpeShowCredits msg:
					_messageHandler.HandleMcpeShowCredits(msg);
					break;
				case McpeAvailableCommands msg:
					_messageHandler.HandleMcpeAvailableCommands(msg);
					break;
				case McpeCommandOutput msg:
					_messageHandler.HandleMcpeCommandOutput(msg);
					break;
				case McpeUpdateTrade msg:
					_messageHandler.HandleMcpeUpdateTrade(msg);
					break;
				case McpeUpdateEquipment msg:
					_messageHandler.HandleMcpeUpdateEquipment(msg);
					break;
				case McpeResourcePackDataInfo msg:
					_messageHandler.HandleMcpeResourcePackDataInfo(msg);
					break;
				case McpeResourcePackChunkData msg:
					_messageHandler.HandleMcpeResourcePackChunkData(msg);
					break;
				case McpeTransfer msg:
					_messageHandler.HandleMcpeTransfer(msg);
					break;
				case McpePlaySound msg:
					_messageHandler.HandleMcpePlaySound(msg);
					break;
				case McpeStopSound msg:
					_messageHandler.HandleMcpeStopSound(msg);
					break;
				case McpeSetTitle msg:
					_messageHandler.HandleMcpeSetTitle(msg);
					break;
				case McpeAddBehaviorTree msg:
					_messageHandler.HandleMcpeAddBehaviorTree(msg);
					break;
				case McpeStructureBlockUpdate msg:
					_messageHandler.HandleMcpeStructureBlockUpdate(msg);
					break;
				case McpeShowStoreOffer msg:
					_messageHandler.HandleMcpeShowStoreOffer(msg);
					break;
				case McpePlayerSkin msg:
					_messageHandler.HandleMcpePlayerSkin(msg);
					break;
				case McpeSubClientLogin msg:
					_messageHandler.HandleMcpeSubClientLogin(msg);
					break;
				case McpeInitiateWebSocketConnection msg:
					_messageHandler.HandleMcpeInitiateWebSocketConnection(msg);
					break;
				case McpeSetLastHurtBy msg:
					_messageHandler.HandleMcpeSetLastHurtBy(msg);
					break;
				case McpeBookEdit msg:
					_messageHandler.HandleMcpeBookEdit(msg);
					break;
				case McpeNpcRequest msg:
					_messageHandler.HandleMcpeNpcRequest(msg);
					break;
				case McpeModalFormRequest msg:
					_messageHandler.HandleMcpeModalFormRequest(msg);
					break;
				case McpeServerSettingsResponse msg:
					_messageHandler.HandleMcpeServerSettingsResponse(msg);
					break;
				case McpeShowProfile msg:
					_messageHandler.HandleMcpeShowProfile(msg);
					break;
				case McpeSetDefaultGameType msg:
					_messageHandler.HandleMcpeSetDefaultGameType(msg);
					break;
				case McpeRemoveObjective msg:
					_messageHandler.HandleMcpeRemoveObjective(msg);
					break;
				case McpeSetDisplayObjective msg:
					_messageHandler.HandleMcpeSetDisplayObjective(msg);
					break;
				case McpeSetScore msg:
					_messageHandler.HandleMcpeSetScore(msg);
					break;
				case McpeLabTable msg:
					_messageHandler.HandleMcpeLabTable(msg);
					break;
				case McpeUpdateBlockSynced msg:
					_messageHandler.HandleMcpeUpdateBlockSynced(msg);
					break;
				case McpeMoveEntityDelta msg:
					_messageHandler.HandleMcpeMoveEntityDelta(msg);
					break;
				case McpeSetScoreboardIdentity msg:
					_messageHandler.HandleMcpeSetScoreboardIdentity(msg);
					break;
				case McpeUpdateSoftEnum msg:
					_messageHandler.HandleMcpeUpdateSoftEnum(msg);
					break;
				case McpeNetworkStackLatency msg:
					_messageHandler.HandleMcpeNetworkStackLatency(msg);
					break;
				case McpeSpawnParticleEffect msg:
					_messageHandler.HandleMcpeSpawnParticleEffect(msg);
					break;
				case McpeAvailableEntityIdentifiers msg:
					_messageHandler.HandleMcpeAvailableEntityIdentifiers(msg);
					break;
				case McpeNetworkChunkPublisherUpdate msg:
					_messageHandler.HandleMcpeNetworkChunkPublisherUpdate(msg);
					break;
				case McpeBiomeDefinitionList msg:
					_messageHandler.HandleMcpeBiomeDefinitionList(msg);
					break;
				case McpeLevelSoundEvent msg:
					_messageHandler.HandleMcpeLevelSoundEvent(msg);
					break;
				case McpeLevelEventGeneric msg:
					_messageHandler.HandleMcpeLevelEventGeneric(msg);
					break;
				case McpeLecternUpdate msg:
					_messageHandler.HandleMcpeLecternUpdate(msg);
					break;
				case McpeClientCacheStatus msg:
					_messageHandler.HandleMcpeClientCacheStatus(msg);
					break;
				case McpeOnScreenTextureAnimation msg:
					_messageHandler.HandleMcpeOnScreenTextureAnimation(msg);
					break;
				case McpeMapCreateLockedCopy msg:
					_messageHandler.HandleMcpeMapCreateLockedCopy(msg);
					break;
				case McpeStructureTemplateDataExportRequest msg:
					_messageHandler.HandleMcpeStructureTemplateDataExportRequest(msg);
					break;
				case McpeStructureTemplateDataExportResponse msg:
					_messageHandler.HandleMcpeStructureTemplateDataExportResponse(msg);
					break;
				case McpeClientCacheMissResponse msg:
					_messageHandler.HandleMcpeClientCacheMissResponse(msg);
					break;
				case McpeEducationSettings msg:
					_messageHandler.HandleMcpeEducationSettings(msg);
					break;
				case McpeEmote msg:
					_messageHandler.HandleMcpeEmote(msg);
					break;
				case McpeMultiplayerSettings msg:
					_messageHandler.HandleMcpeMultiplayerSettings(msg);
					break;
				case McpeCompletedUsingItem msg:
					_messageHandler.HandleMcpeCompletedUsingItem(msg);
					break;
				case McpeNetworkSettings msg:
					_messageHandler.HandleMcpeNetworkSettings(msg);
					break;
				case McpeCreativeContent msg:
					_messageHandler.HandleMcpeCreativeContent(msg);
					break;
				case McpePlayerEnchantOptions msg:
					_messageHandler.HandleMcpePlayerEnchantOptions(msg);
					break;
				case McpeItemStackResponse msg:
					_messageHandler.HandleMcpeItemStackResponse(msg);
					break;
				case McpePlayerArmorDamage msg:
					_messageHandler.HandleMcpePlayerArmorDamage(msg);
					break;
				case McpeCodeBuilder msg:
					_messageHandler.HandleMcpeCodeBuilder(msg);
					break;
				case McpePositionTrackingDbServerBroadcast msg:
					_messageHandler.HandleMcpePositionTrackingDbServerBroadcast(msg);
					break;
				case McpeDebugInfo msg:
					_messageHandler.HandleMcpeDebugInfo(msg);
					break;
				case McpeMotionPredictionHints msg:
					_messageHandler.HandleMcpeMotionPredictionHints(msg);
					break;
				case McpeAnimateEntity msg:
					_messageHandler.HandleMcpeAnimateEntity(msg);
					break;
				case McpeCameraShake msg:
					_messageHandler.HandleMcpeCameraShake(msg);
					break;
				case McpePlayerFog msg:
					_messageHandler.HandleMcpePlayerFog(msg);
					break;
				case McpeCorrectPlayerMovePrediction msg:
					_messageHandler.HandleMcpeCorrectPlayerMovePrediction(msg);
					break;
				case McpeItemComponent msg:
					_messageHandler.HandleMcpeItemComponent(msg);
					break;
				case McpeClientboundDebugRenderer msg:
					_messageHandler.HandleMcpeClientboundDebugRenderer(msg);
					break;
				case McpeSyncEntityProperty msg:
					_messageHandler.HandleMcpeSyncEntityProperty(msg);
					break;
				case McpeAddVolumeEntity msg:
					_messageHandler.HandleMcpeAddVolumeEntity(msg);
					break;
				case McpeRemoveVolumeEntity msg:
					_messageHandler.HandleMcpeRemoveVolumeEntity(msg);
					break;
				case McpeSimulationType msg:
					_messageHandler.HandleMcpeSimulationType(msg);
					break;
				case McpeNpcDialogue msg:
					_messageHandler.HandleMcpeNpcDialogue(msg);
					break;
				case McpeEduUriResource msg:
					_messageHandler.HandleMcpeEduUriResource(msg);
					break;
				case McpeUpdateSubChunkBlocksPacket msg:
					_messageHandler.HandleMcpeUpdateSubChunkBlocksPacket(msg);
					break;
				case McpeSubChunkPacket msg:
					_messageHandler.HandleMcpeSubChunkPacket(msg);
					break;
				case McpePlayerStartItemCooldown msg:
					_messageHandler.HandleMcpePlayerStartItemCooldown(msg);
					break;
				case McpeScriptMessage msg:
					_messageHandler.HandleMcpeScriptMessage(msg);
					break;
				case McpeTickingAreasLoadStatus msg:
					_messageHandler.HandleMcpeTickingAreasLoadStatus(msg);
					break;
				case McpeDimensionData msg:
					_messageHandler.HandleMcpeDimensionData(msg);
					break;
				case McpeAgentActionEvent msg:
					_messageHandler.HandleMcpeAgentActionEvent(msg);
					break;
				case McpeLessonProgress msg:
					_messageHandler.HandleMcpeLessonProgress(msg);
					break;
				case McpeToastRequest msg:
					_messageHandler.HandleMcpeToastRequest(msg);
					break;
				case McpeUpdateAbilities msg:
					_messageHandler.HandleMcpeUpdateAbilities(msg);
					break;
				case McpeUpdateAdventureSettings msg:
					_messageHandler.HandleMcpeUpdateAdventureSettings(msg);
					break;
				case McpeDeathInfo msg:
					_messageHandler.HandleMcpeDeathInfo(msg);
					break;
				case McpeEditorNetwork msg:
					_messageHandler.HandleMcpeEditorNetwork(msg);
					break;
				case McpeFeatureRegistry msg:
					_messageHandler.HandleMcpeFeatureRegistry(msg);
					break;
				case McpeServerStats msg:
					_messageHandler.HandleMcpeServerStats(msg);
					break;
				case McpeGameTestResults msg:
					_messageHandler.HandleMcpeGameTestResults(msg);
					break;
				case McpeUpdateClientInputLocks msg:
					_messageHandler.HandleMcpeUpdateClientInputLocks(msg);
					break;
				case McpeCameraPresets msg:
					_messageHandler.HandleMcpeCameraPresets(msg);
					break;
				case McpeUnlockedRecipes msg:
					_messageHandler.HandleMcpeUnlockedRecipes(msg);
					break;
				case McpeCameraInstruction msg:
					_messageHandler.HandleMcpeCameraInstruction(msg);
					break;
				case McpeTrimData msg:
					_messageHandler.HandleMcpeTrimData(msg);
					break;
				case McpeOpenSign msg:
					_messageHandler.HandleMcpeOpenSign(msg);
					break;
				case McpeAgentAnimation msg:
					_messageHandler.HandleMcpeAgentAnimation(msg);
					break;
				case McpeRefreshEntitlements msg:
					_messageHandler.HandleMcpeRefreshEntitlements(msg);
					break;
				case McpeSetHud msg:
					_messageHandler.HandleMcpeSetHud(msg);
					break;
				case McpeAwardAchievement msg:
					_messageHandler.HandleMcpeAwardAchievement(msg);
					break;
				case McpeClientboundCloseForm msg:
					_messageHandler.HandleMcpeClientboundCloseForm(msg);
					break;
				case McpeJigsawStructureData msg:
					_messageHandler.HandleMcpeJigsawStructureData(msg);
					break;
				case McpeCurrentStructureFeature msg:
					_messageHandler.HandleMcpeCurrentStructureFeature(msg);
					break;
				case McpeCameraAimAssist msg:
					_messageHandler.HandleMcpeCameraAimAssist(msg);
					break;
				case McpeContainerRegistryCleanup msg:
					_messageHandler.HandleMcpeContainerRegistryCleanup(msg);
					break;
				case McpeMovementEffect msg:
					_messageHandler.HandleMcpeMovementEffect(msg);
					break;
				case McpeCameraAimAssistPresets msg:
					_messageHandler.HandleMcpeCameraAimAssistPresets(msg);
					break;
				case McpePlayerVideoCapture msg:
					_messageHandler.HandleMcpePlayerVideoCapture(msg);
					break;
				case McpePlayerUpdateEntityOverrides msg:
					_messageHandler.HandleMcpePlayerUpdateEntityOverrides(msg);
					break;
				case McpePlayerLocation msg:
					_messageHandler.HandleMcpePlayerLocation(msg);
					break;
				case McpeClientboundControlSchemeSet msg:
					_messageHandler.HandleMcpeClientboundControlSchemeSet(msg);
					break;
				case McpePrimitiveShapes msg:
					_messageHandler.HandleMcpePrimitiveShapes(msg);
					break;
				case McpeClientboundDataStore msg:
					_messageHandler.HandleMcpeClientboundDataStore(msg);
					break;
				case McpeGraphicsOverrideParameter msg:
					_messageHandler.HandleMcpeGraphicsOverrideParameter(msg);
					break;
				case McpeClientboundDataDrivenUiShowScreen msg:
					_messageHandler.HandleMcpeClientboundDataDrivenUiShowScreen(msg);
					break;
				case McpeClientboundDataDrivenUiCloseScreen msg:
					_messageHandler.HandleMcpeClientboundDataDrivenUiCloseScreen(msg);
					break;
				case McpeClientboundDataDrivenUiReload msg:
					_messageHandler.HandleMcpeClientboundDataDrivenUiReload(msg);
					break;
				case McpeClientboundTextureShift msg:
					_messageHandler.HandleMcpeClientboundTextureShift(msg);
					break;
				case McpeVoxelShapes msg:
					_messageHandler.HandleMcpeVoxelShapes(msg);
					break;
				case McpeCameraSpline msg:
					_messageHandler.HandleMcpeCameraSpline(msg);
					break;
				case McpeCameraAimAssistActorPriority msg:
					_messageHandler.HandleMcpeCameraAimAssistActorPriority(msg);
					break;
				case McpeLocatorBar msg:
					_messageHandler.HandleMcpeLocatorBar(msg);
					break;
				case McpeSyncWorldClocks msg:
					_messageHandler.HandleMcpeSyncWorldClocks(msg);
					break;
				case McpeClientboundAttributeLayerSync msg:
					_messageHandler.HandleMcpeClientboundAttributeLayerSync(msg);
					break;
				case McpeServerStoreInfo msg:
					_messageHandler.HandleMcpeServerStoreInfo(msg);
					break;
				case McpeServerPresenceInfo msg:
					_messageHandler.HandleMcpeServerPresenceInfo(msg);
					break;
				case McpeClientboundUpdateSoundData msg:
					_messageHandler.HandleMcpeClientboundUpdateSoundData(msg);
					break;
				case McpeSendPartyDestinationCookie msg:
					_messageHandler.HandleMcpeSendPartyDestinationCookie(msg);
					break;
				case McpeSetPlayerFurnaceOptions msg:
					_messageHandler.HandleMcpeSetPlayerFurnaceOptions(msg);
					break;
				case McpeRecordStarted msg:
					_messageHandler.HandleMcpeRecordStarted(msg);
					break;
				default:
					return false;
			}

			return true;
		}
	}

	public class PacketFactory
	{
		public static ICustomPacketFactory CustomPacketFactory { get; set; } = null;

		public static Packet Create(int messageId, ReadOnlyMemory<byte> buffer, string ns)
		{
			Packet packet = CustomPacketFactory?.Create(messageId, buffer, ns);
			if (packet != null) return packet;

			if(ns == "raknet") 
			{
				switch (messageId)
				{
					case 0x01:
						return UnconnectedPing.CreateObject().Decode(buffer);
					case 0x1c:
						return UnconnectedPong.CreateObject().Decode(buffer);
					case 0xfe:
						return McpeWrapper.CreateObject().Decode(buffer);
				}
			} else if(ns == "ftl") 
			{
				switch (messageId)
				{
					case 0x01:
						return FtlCreatePlayer.CreateObject().Decode(buffer);
				}
			} else {

				switch (messageId)
				{
					case 0x01:
						return McpeLogin.CreateObject().Decode(buffer);
					case 0x02:
						return McpePlayStatus.CreateObject().Decode(buffer);
					case 0x03:
						return McpeServerToClientHandshake.CreateObject().Decode(buffer);
					case 0x04:
						return McpeClientToServerHandshake.CreateObject().Decode(buffer);
					case 0x05:
						return McpeDisconnect.CreateObject().Decode(buffer);
					case 0x06:
						return McpeResourcePacksInfo.CreateObject().Decode(buffer);
					case 0x07:
						return McpeResourcePackStack.CreateObject().Decode(buffer);
					case 0x08:
						return McpeResourcePackClientResponse.CreateObject().Decode(buffer);
					case 0x09:
						return McpeText.CreateObject().Decode(buffer);
					case 0x0a:
						return McpeSetTime.CreateObject().Decode(buffer);
					case 0x0b:
						return McpeStartGame.CreateObject().Decode(buffer);
					case 0x0c:
						return McpeAddPlayer.CreateObject().Decode(buffer);
					case 0x0d:
						return McpeAddEntity.CreateObject().Decode(buffer);
					case 0x0e:
						return McpeRemoveEntity.CreateObject().Decode(buffer);
					case 0x0f:
						return McpeAddItemEntity.CreateObject().Decode(buffer);
					case 0x10:
						return McpeServerPlayerPostMovePosition.CreateObject().Decode(buffer);
					case 0x11:
						return McpeTakeItemEntity.CreateObject().Decode(buffer);
					case 0x12:
						return McpeMoveEntity.CreateObject().Decode(buffer);
					case 0x13:
						return McpeMovePlayer.CreateObject().Decode(buffer);
					case 0x15:
						return McpeUpdateBlock.CreateObject().Decode(buffer);
					case 0x16:
						return McpeAddPainting.CreateObject().Decode(buffer);
					case 0x19:
						return McpeLevelEvent.CreateObject().Decode(buffer);
					case 0x1a:
						return McpeBlockEvent.CreateObject().Decode(buffer);
					case 0x1b:
						return McpeEntityEvent.CreateObject().Decode(buffer);
					case 0x1c:
						return McpeMobEffect.CreateObject().Decode(buffer);
					case 0x1d:
						return McpeUpdateAttributes.CreateObject().Decode(buffer);
					case 0x1e:
						return McpeInventoryTransaction.CreateObject().Decode(buffer);
					case 0x1f:
						return McpeMobEquipment.CreateObject().Decode(buffer);
					case 0x20:
						return McpeMobArmorEquipment.CreateObject().Decode(buffer);
					case 0x21:
						return McpeInteract.CreateObject().Decode(buffer);
					case 0x22:
						return McpeBlockPickRequest.CreateObject().Decode(buffer);
					case 0x23:
						return McpeEntityPickRequest.CreateObject().Decode(buffer);
					case 0x24:
						return McpePlayerAction.CreateObject().Decode(buffer);
					case 0x26:
						return McpeHurtArmor.CreateObject().Decode(buffer);
					case 0x27:
						return McpeSetEntityData.CreateObject().Decode(buffer);
					case 0x28:
						return McpeSetEntityMotion.CreateObject().Decode(buffer);
					case 0x29:
						return McpeSetEntityLink.CreateObject().Decode(buffer);
					case 0x2a:
						return McpeSetHealth.CreateObject().Decode(buffer);
					case 0x2b:
						return McpeSetSpawnPosition.CreateObject().Decode(buffer);
					case 0x2c:
						return McpeAnimate.CreateObject().Decode(buffer);
					case 0x2d:
						return McpeRespawn.CreateObject().Decode(buffer);
					case 0x2e:
						return McpeContainerOpen.CreateObject().Decode(buffer);
					case 0x2f:
						return McpeContainerClose.CreateObject().Decode(buffer);
					case 0x30:
						return McpePlayerHotbar.CreateObject().Decode(buffer);
					case 0x31:
						return McpeInventoryContent.CreateObject().Decode(buffer);
					case 0x32:
						return McpeInventorySlot.CreateObject().Decode(buffer);
					case 0x33:
						return McpeContainerSetData.CreateObject().Decode(buffer);
					case 0x34:
						return McpeCraftingData.CreateObject().Decode(buffer);
					case 0x36:
						return McpeGuiDataPickItem.CreateObject().Decode(buffer);
					case 0x38:
						return McpeBlockEntityData.CreateObject().Decode(buffer);
					case 0x3a:
						return McpeLevelChunk.CreateObject().Decode(buffer);
					case 0x3b:
						return McpeSetCommandsEnabled.CreateObject().Decode(buffer);
					case 0x3c:
						return McpeSetDifficulty.CreateObject().Decode(buffer);
					case 0x3d:
						return McpeChangeDimension.CreateObject().Decode(buffer);
					case 0x3e:
						return McpeSetPlayerGameType.CreateObject().Decode(buffer);
					case 0x3f:
						return McpePlayerList.CreateObject().Decode(buffer);
					case 0x40:
						return McpeSimpleEvent.CreateObject().Decode(buffer);
					case 0x41:
						return McpeTelemetryEvent.CreateObject().Decode(buffer);
					case 0x42:
						return McpeSpawnExperienceOrb.CreateObject().Decode(buffer);
					case 0x43:
						return McpeClientboundMapItemData.CreateObject().Decode(buffer);
					case 0x44:
						return McpeMapInfoRequest.CreateObject().Decode(buffer);
					case 0x45:
						return McpeRequestChunkRadius.CreateObject().Decode(buffer);
					case 0x46:
						return McpeChunkRadiusUpdate.CreateObject().Decode(buffer);
					case 0x48:
						return McpeGameRulesChanged.CreateObject().Decode(buffer);
					case 0x49:
						return McpeCamera.CreateObject().Decode(buffer);
					case 0x4a:
						return McpeBossEvent.CreateObject().Decode(buffer);
					case 0x4b:
						return McpeShowCredits.CreateObject().Decode(buffer);
					case 0x4c:
						return McpeAvailableCommands.CreateObject().Decode(buffer);
					case 0x4d:
						return McpeCommandRequest.CreateObject().Decode(buffer);
					case 0x4e:
						return McpeCommandBlockUpdate.CreateObject().Decode(buffer);
					case 0x4f:
						return McpeCommandOutput.CreateObject().Decode(buffer);
					case 0x50:
						return McpeUpdateTrade.CreateObject().Decode(buffer);
					case 0x51:
						return McpeUpdateEquipment.CreateObject().Decode(buffer);
					case 0x52:
						return McpeResourcePackDataInfo.CreateObject().Decode(buffer);
					case 0x53:
						return McpeResourcePackChunkData.CreateObject().Decode(buffer);
					case 0x54:
						return McpeResourcePackChunkRequest.CreateObject().Decode(buffer);
					case 0x55:
						return McpeTransfer.CreateObject().Decode(buffer);
					case 0x56:
						return McpePlaySound.CreateObject().Decode(buffer);
					case 0x57:
						return McpeStopSound.CreateObject().Decode(buffer);
					case 0x58:
						return McpeSetTitle.CreateObject().Decode(buffer);
					case 0x59:
						return McpeAddBehaviorTree.CreateObject().Decode(buffer);
					case 0x5a:
						return McpeStructureBlockUpdate.CreateObject().Decode(buffer);
					case 0x5b:
						return McpeShowStoreOffer.CreateObject().Decode(buffer);
					case 0x5c:
						return McpePurchaseReceipt.CreateObject().Decode(buffer);
					case 0x5d:
						return McpePlayerSkin.CreateObject().Decode(buffer);
					case 0x5e:
						return McpeSubClientLogin.CreateObject().Decode(buffer);
					case 0x5f:
						return McpeInitiateWebSocketConnection.CreateObject().Decode(buffer);
					case 0x60:
						return McpeSetLastHurtBy.CreateObject().Decode(buffer);
					case 0x61:
						return McpeBookEdit.CreateObject().Decode(buffer);
					case 0x62:
						return McpeNpcRequest.CreateObject().Decode(buffer);
					case 0x63:
						return McpePhotoTransfer.CreateObject().Decode(buffer);
					case 0x64:
						return McpeModalFormRequest.CreateObject().Decode(buffer);
					case 0x65:
						return McpeModalFormResponse.CreateObject().Decode(buffer);
					case 0x66:
						return McpeServerSettingsRequest.CreateObject().Decode(buffer);
					case 0x67:
						return McpeServerSettingsResponse.CreateObject().Decode(buffer);
					case 0x68:
						return McpeShowProfile.CreateObject().Decode(buffer);
					case 0x69:
						return McpeSetDefaultGameType.CreateObject().Decode(buffer);
					case 0x6a:
						return McpeRemoveObjective.CreateObject().Decode(buffer);
					case 0x6b:
						return McpeSetDisplayObjective.CreateObject().Decode(buffer);
					case 0x6c:
						return McpeSetScore.CreateObject().Decode(buffer);
					case 0x6d:
						return McpeLabTable.CreateObject().Decode(buffer);
					case 0x6e:
						return McpeUpdateBlockSynced.CreateObject().Decode(buffer);
					case 0x6f:
						return McpeMoveEntityDelta.CreateObject().Decode(buffer);
					case 0x70:
						return McpeSetScoreboardIdentity.CreateObject().Decode(buffer);
					case 0x71:
						return McpeSetLocalPlayerAsInitialized.CreateObject().Decode(buffer);
					case 0x72:
						return McpeUpdateSoftEnum.CreateObject().Decode(buffer);
					case 0x73:
						return McpeNetworkStackLatency.CreateObject().Decode(buffer);
					case 0x76:
						return McpeSpawnParticleEffect.CreateObject().Decode(buffer);
					case 0x77:
						return McpeAvailableEntityIdentifiers.CreateObject().Decode(buffer);
					case 0x79:
						return McpeNetworkChunkPublisherUpdate.CreateObject().Decode(buffer);
					case 0x7a:
						return McpeBiomeDefinitionList.CreateObject().Decode(buffer);
					case 0x7b:
						return McpeLevelSoundEvent.CreateObject().Decode(buffer);
					case 0x7c:
						return McpeLevelEventGeneric.CreateObject().Decode(buffer);
					case 0x7d:
						return McpeLecternUpdate.CreateObject().Decode(buffer);
					case 0x81:
						return McpeClientCacheStatus.CreateObject().Decode(buffer);
					case 0x82:
						return McpeOnScreenTextureAnimation.CreateObject().Decode(buffer);
					case 0x83:
						return McpeMapCreateLockedCopy.CreateObject().Decode(buffer);
					case 0x84:
						return McpeStructureTemplateDataExportRequest.CreateObject().Decode(buffer);
					case 0x85:
						return McpeStructureTemplateDataExportResponse.CreateObject().Decode(buffer);
					case 0x87:
						return McpeClientCacheBlobStatus.CreateObject().Decode(buffer);
					case 0x88:
						return McpeClientCacheMissResponse.CreateObject().Decode(buffer);
					case 0x89:
						return McpeEducationSettings.CreateObject().Decode(buffer);
					case 0x8a:
						return McpeEmote.CreateObject().Decode(buffer);
					case 0x8b:
						return McpeMultiplayerSettings.CreateObject().Decode(buffer);
					case 0x8c:
						return McpeSettingsCommand.CreateObject().Decode(buffer);
					case 0x8d:
						return McpeAnvilDamage.CreateObject().Decode(buffer);
					case 0x8e:
						return McpeCompletedUsingItem.CreateObject().Decode(buffer);
					case 0x8f:
						return McpeNetworkSettings.CreateObject().Decode(buffer);
					case 0x90:
						return McpePlayerAuthInput.CreateObject().Decode(buffer);
					case 0x91:
						return McpeCreativeContent.CreateObject().Decode(buffer);
					case 0x92:
						return McpePlayerEnchantOptions.CreateObject().Decode(buffer);
					case 0x93:
						return McpeItemStackRequest.CreateObject().Decode(buffer);
					case 0x94:
						return McpeItemStackResponse.CreateObject().Decode(buffer);
					case 0x95:
						return McpePlayerArmorDamage.CreateObject().Decode(buffer);
					case 0x96:
						return McpeCodeBuilder.CreateObject().Decode(buffer);
					case 0x97:
						return McpeUpdatePlayerGameType.CreateObject().Decode(buffer);
					case 0x98:
						return McpeEmoteList.CreateObject().Decode(buffer);
					case 0x99:
						return McpePositionTrackingDbServerBroadcast.CreateObject().Decode(buffer);
					case 0x9a:
						return McpePositionTrackingDbClientRequest.CreateObject().Decode(buffer);
					case 0x9b:
						return McpeDebugInfo.CreateObject().Decode(buffer);
					case 0x9c:
						return McpePacketViolationWarning.CreateObject().Decode(buffer);
					case 0x9d:
						return McpeMotionPredictionHints.CreateObject().Decode(buffer);
					case 0x9e:
						return McpeAnimateEntity.CreateObject().Decode(buffer);
					case 0x9f:
						return McpeCameraShake.CreateObject().Decode(buffer);
					case 0xa0:
						return McpePlayerFog.CreateObject().Decode(buffer);
					case 0xa1:
						return McpeCorrectPlayerMovePrediction.CreateObject().Decode(buffer);
					case 0xa2:
						return McpeItemComponent.CreateObject().Decode(buffer);
					case 0xa4:
						return McpeClientboundDebugRenderer.CreateObject().Decode(buffer);
					case 0xa5:
						return McpeSyncEntityProperty.CreateObject().Decode(buffer);
					case 0xa6:
						return McpeAddVolumeEntity.CreateObject().Decode(buffer);
					case 0xa7:
						return McpeRemoveVolumeEntity.CreateObject().Decode(buffer);
					case 0xa8:
						return McpeSimulationType.CreateObject().Decode(buffer);
					case 0xa9:
						return McpeNpcDialogue.CreateObject().Decode(buffer);
					case 0xaa:
						return McpeEduUriResource.CreateObject().Decode(buffer);
					case 0xab:
						return McpeCreatePhoto.CreateObject().Decode(buffer);
					case 0xac:
						return McpeUpdateSubChunkBlocksPacket.CreateObject().Decode(buffer);
					case 0xae:
						return McpeSubChunkPacket.CreateObject().Decode(buffer);
					case 0xaf:
						return McpeSubChunkRequestPacket.CreateObject().Decode(buffer);
					case 0xb0:
						return McpePlayerStartItemCooldown.CreateObject().Decode(buffer);
					case 0xb1:
						return McpeScriptMessage.CreateObject().Decode(buffer);
					case 0xb2:
						return McpeCodeBuilderSource.CreateObject().Decode(buffer);
					case 0xb3:
						return McpeTickingAreasLoadStatus.CreateObject().Decode(buffer);
					case 0xb4:
						return McpeDimensionData.CreateObject().Decode(buffer);
					case 0xb5:
						return McpeAgentActionEvent.CreateObject().Decode(buffer);
					case 0xb6:
						return McpeChangeMobProperty.CreateObject().Decode(buffer);
					case 0xb7:
						return McpeLessonProgress.CreateObject().Decode(buffer);
					case 0xb8:
						return McpeRequestAbility.CreateObject().Decode(buffer);
					case 0xb9:
						return McpeRequestPermissions.CreateObject().Decode(buffer);
					case 0xba:
						return McpeToastRequest.CreateObject().Decode(buffer);
					case 0xbb:
						return McpeUpdateAbilities.CreateObject().Decode(buffer);
					case 0xbc:
						return McpeUpdateAdventureSettings.CreateObject().Decode(buffer);
					case 0xbd:
						return McpeDeathInfo.CreateObject().Decode(buffer);
					case 0xbe:
						return McpeEditorNetwork.CreateObject().Decode(buffer);
					case 0xbf:
						return McpeFeatureRegistry.CreateObject().Decode(buffer);
					case 0xc0:
						return McpeServerStats.CreateObject().Decode(buffer);
					case 0xc1:
						return McpeRequestNetworkSettings.CreateObject().Decode(buffer);
					case 0xc2:
						return McpeGameTestRequest.CreateObject().Decode(buffer);
					case 0xc3:
						return McpeGameTestResults.CreateObject().Decode(buffer);
					case 0xc4:
						return McpeUpdateClientInputLocks.CreateObject().Decode(buffer);
					case 0xc6:
						return McpeCameraPresets.CreateObject().Decode(buffer);
					case 0xc7:
						return McpeUnlockedRecipes.CreateObject().Decode(buffer);
					case 0x12c:
						return McpeCameraInstruction.CreateObject().Decode(buffer);
					case 0x12e:
						return McpeTrimData.CreateObject().Decode(buffer);
					case 0x12f:
						return McpeOpenSign.CreateObject().Decode(buffer);
					case 0x130:
						return McpeAgentAnimation.CreateObject().Decode(buffer);
					case 0x131:
						return McpeRefreshEntitlements.CreateObject().Decode(buffer);
					case 0x132:
						return McpePlayerToggleCrafterSlotRequest.CreateObject().Decode(buffer);
					case 0x133:
						return McpeSetPlayerInventoryOptions.CreateObject().Decode(buffer);
					case 0x134:
						return McpeSetHud.CreateObject().Decode(buffer);
					case 0x135:
						return McpeAwardAchievement.CreateObject().Decode(buffer);
					case 0x136:
						return McpeClientboundCloseForm.CreateObject().Decode(buffer);
					case 0x138:
						return McpeServerBoundLoadingScreen.CreateObject().Decode(buffer);
					case 0x139:
						return McpeJigsawStructureData.CreateObject().Decode(buffer);
					case 0x13a:
						return McpeCurrentStructureFeature.CreateObject().Decode(buffer);
					case 0x13b:
						return McpeServerBoundDiagnostics.CreateObject().Decode(buffer);
					case 0x13c:
						return McpeCameraAimAssist.CreateObject().Decode(buffer);
					case 0x13d:
						return McpeContainerRegistryCleanup.CreateObject().Decode(buffer);
					case 0x13e:
						return McpeMovementEffect.CreateObject().Decode(buffer);
					case 0x140:
						return McpeCameraAimAssistPresets.CreateObject().Decode(buffer);
					case 0x141:
						return McpeClientCameraAimAssist.CreateObject().Decode(buffer);
					case 0x142:
						return McpeClientMovementPredictionSync.CreateObject().Decode(buffer);
					case 0x143:
						return McpeUpdateClientOptions.CreateObject().Decode(buffer);
					case 0x144:
						return McpePlayerVideoCapture.CreateObject().Decode(buffer);
					case 0x145:
						return McpePlayerUpdateEntityOverrides.CreateObject().Decode(buffer);
					case 0x146:
						return McpePlayerLocation.CreateObject().Decode(buffer);
					case 0x147:
						return McpeClientboundControlSchemeSet.CreateObject().Decode(buffer);
					case 0x148:
						return McpePrimitiveShapes.CreateObject().Decode(buffer);
					case 0x149:
						return McpeServerboundPackSettingChange.CreateObject().Decode(buffer);
					case 0x14a:
						return McpeClientboundDataStore.CreateObject().Decode(buffer);
					case 0x14b:
						return McpeGraphicsOverrideParameter.CreateObject().Decode(buffer);
					case 0x14c:
						return McpeServerboundDataStore.CreateObject().Decode(buffer);
					case 0x14d:
						return McpeClientboundDataDrivenUiShowScreen.CreateObject().Decode(buffer);
					case 0x14e:
						return McpeClientboundDataDrivenUiCloseScreen.CreateObject().Decode(buffer);
					case 0x14f:
						return McpeClientboundDataDrivenUiReload.CreateObject().Decode(buffer);
					case 0x150:
						return McpeClientboundTextureShift.CreateObject().Decode(buffer);
					case 0x151:
						return McpeVoxelShapes.CreateObject().Decode(buffer);
					case 0x152:
						return McpeCameraSpline.CreateObject().Decode(buffer);
					case 0x153:
						return McpeCameraAimAssistActorPriority.CreateObject().Decode(buffer);
					case 0x154:
						return McpeResourcePacksReadyForValidation.CreateObject().Decode(buffer);
					case 0x155:
						return McpeLocatorBar.CreateObject().Decode(buffer);
					case 0x156:
						return McpePartyChanged.CreateObject().Decode(buffer);
					case 0x157:
						return McpeServerboundDataDrivenScreenClosed.CreateObject().Decode(buffer);
					case 0x158:
						return McpeSyncWorldClocks.CreateObject().Decode(buffer);
					case 0x159:
						return McpeClientboundAttributeLayerSync.CreateObject().Decode(buffer);
					case 0x15a:
						return McpeServerStoreInfo.CreateObject().Decode(buffer);
					case 0x15b:
						return McpeServerPresenceInfo.CreateObject().Decode(buffer);
					case 0x15c:
						return McpeClientboundUpdateSoundData.CreateObject().Decode(buffer);
					case 0x15d:
						return McpeSendPartyDestinationCookie.CreateObject().Decode(buffer);
					case 0x15e:
						return McpePartyDestinationCookieResponse.CreateObject().Decode(buffer);
					case 0x15f:
						return McpeSetPlayerFurnaceOptions.CreateObject().Decode(buffer);
					case 0x160:
						return McpeRecordStarted.CreateObject().Decode(buffer);
				}
			}

			return null;
		}
	}
}