#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE. 
// The License is based on the Mozilla Public License Version 1.1, but Sections 14 
// and 15 have been added to cover use of software over a computer network and 
// provide for limited attribution for the Original Developer. In addition, Exhibit A has 
// been modified to be consistent with Exhibit B.
// 
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
// 
// The Original Code is MiNET.
// 
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
// 
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson. 
// All Rights Reserved.

#endregion

using System;
using System.Collections.Generic;
using MiNET.Items;
using MiNET.Utils;
using Newtonsoft.Json.Linq;

namespace MiNET
{
	// ReSharper disable RedundantArgumentDefaultValue
	// The creative tab groups (Items/Data/creative_groups.json, generated by MiNET.BlockGen from
	// the BDS memory extraction and checked against a captured BDS creative_content frame): the
	// group list (category, translation name, icon stack) and, per creative entry, the index of the
	// group it belongs to (aligned with CreativeInventoryItems order).
	public class CreativeGroupData
	{
		public List<CreativeGroupDef> Groups { get; set; }
		public List<CreativeEntryDef> Entries { get; set; }
		public List<int> EntryGroups { get; set; }
	}

	// A creative entry's exact wire identity. The catalog packet is built from these verbatim;
	// InventoryUtils.CreativeInventoryItems (same order, same indexes) is only used server-side to
	// resolve craft-creative requests into real items.
	public class CreativeEntryDef
	{
		public int GroupIndex { get; set; }
		public int NetworkId { get; set; }
		public short Metadata { get; set; }
		public int RuntimeId { get; set; }

		// The stack's user data as typed JSON NBT, e.g. a firework's explosions. Null for a plain
		// stack. Read through TypedNbtJson into the item's ExtraData.
		public JObject Nbt { get; set; }
	}

	public class CreativeGroupDef
	{
		public int Category { get; set; }
		public string Name { get; set; }
		public string Icon { get; set; }
		// The icon's exact wire identity, sent verbatim rather than re-derived through the item
		// factory (which cannot reconstruct it for every icon).
		public int IconNetworkId { get; set; }
		public short IconMetadata { get; set; }
		public int IconRuntimeId { get; set; }
		// Icon user data as typed JSON NBT, e.g. the enchanted book group icon's stored
		// enchantment. Null for plain icons.
		public JObject IconNbt { get; set; }
	}

	public static class InventoryUtils
	{
		public static readonly Lazy<CreativeGroupData> CreativeGroups = new Lazy<CreativeGroupData>(() =>
			ResourceUtil.ReadResource<CreativeGroupData>("creative_groups.json", typeof(Items.Item), "Data"));

		/// <summary>
		///     The creative catalog as real items, in the order the catalog packet sends it, so an
		///     index resolves to something the server can put in a slot. Built from the same entries
		///     the packet is written from (creative_groups.json), keyed by network id through the
		///     item registry, so the catalog and this list cannot drift apart.
		/// </summary>
		public static IReadOnlyList<Items.Item> CreativeInventoryItems => _creativeItems.Value;

		private static readonly Lazy<List<Items.Item>> _creativeItems = new Lazy<List<Items.Item>>(() =>
		{
			var items = new List<Items.Item>();
			foreach (CreativeEntryDef entry in CreativeGroups.Value.Entries)
			{
				string name = ItemFactory.ItemRegistry.GetName((short) entry.NetworkId);
				Items.Item item = name == null ? new ItemAir() : ItemFactory.GetItemByName(name, entry.Metadata);
				item.RuntimeId = entry.RuntimeId;
				items.Add(item);
			}

			return items;
		});
	}
}